### PR TITLE
mpich 3 works with 4

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by hmaarrfk** [comment]
Question: Have you released an MPICH release with the loosened pin for version 3?

Should you specify that the pin ends with `",<4.0.0a0"`?

**Comment by beckermr** [comment]
The ends of the pins don't need to be specified or at least I cannot think of a reason why. 

Instead of releasing a looser mpich 3, we should bump to 4 in the global pinnings without a migration.

**Comment by beckermr** [comment]
We need to merge https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2580 after this PR

**Pull request merged**
