### PR TITLE
Fix cfn-lint dependency on aws-sam-translator

### PR DESCRIPTION
**Pull request by maresb**
The cfn-lint feedstock has not been reliably updating the aws-sam-translator dependency. This leads to lots of invalid environments involving older packages when fsspec is involved, due to the behavior described in https://github.com/conda-forge/filesystem-spec-feedstock/issues/79. Going forward, the issue has been fixed in https://github.com/conda-forge/cfn-lint-feedstock/pull/177.

Checklist

* [ ] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/patch_yaml/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [X] Ran `python show_diff.py` and posted the output as part of the PR.
* [X] Modifications won't affect packages built in the future. 

### NOTE: I'm just now seeing the static YAML option.

This is very exciting since this repo is in desperate need of a more declarative system. I hope that, due to time constrains, you could just this one time waive this requirement for me so that I don't have to redo my work on this from scratch. Thanks!

```diff

noarch::cfn-lint-0.22.0-py_0.tar.bz2
-    "aws-sam-translator >=1.10.0",
+    "aws-sam-translator >=1.12.0",
noarch::cfn-lint-0.56.3-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.56.4-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.57.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.58.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.58.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.58.2-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.58.3-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.58.4-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.42.0",
noarch::cfn-lint-0.59.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.45.0",
noarch::cfn-lint-0.59.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.45.0",
noarch::cfn-lint-0.60.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.45.0",
noarch::cfn-lint-0.60.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.45.0",
noarch::cfn-lint-0.61.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.45.0",
noarch::cfn-lint-0.61.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.46.0",
noarch::cfn-lint-0.61.2-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.46.0",
noarch::cfn-lint-0.61.3-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.47.0",
noarch::cfn-lint-0.61.4-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.48.0",
noarch::cfn-lint-0.61.5-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.49.0",
noarch::cfn-lint-0.62.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.63.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.63.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.63.2-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.64.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.64.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.65.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.50.0",
noarch::cfn-lint-0.65.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.51.0",
noarch::cfn-lint-0.66.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.51.0",
noarch::cfn-lint-0.66.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.51.0",
noarch::cfn-lint-0.67.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.52.0",
noarch::cfn-lint-0.68.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.53.0",
noarch::cfn-lint-0.68.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.53.0",
noarch::cfn-lint-0.69.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.53.0",
noarch::cfn-lint-0.69.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.53.0",
noarch::cfn-lint-0.70.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.53.0",
noarch::cfn-lint-0.71.0-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.53.0",
noarch::cfn-lint-0.71.1-pyhd8ed1ab_0.tar.bz2
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.54.0",
noarch::cfn-lint-0.72.0-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.54.0",
noarch::cfn-lint-0.72.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.54.0",
noarch::cfn-lint-0.72.10-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.57.0",
noarch::cfn-lint-0.72.2-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.55.0",
noarch::cfn-lint-0.72.3-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.55.0",
noarch::cfn-lint-0.72.4-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.55.0",
noarch::cfn-lint-0.72.5-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.40.0",
+    "aws-sam-translator >=1.55.0",
noarch::cfn-lint-0.72.7-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.56.0",
noarch::cfn-lint-0.72.7-pyhd8ed1ab_1.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.56.0",
noarch::cfn-lint-0.72.8-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.56.0",
noarch::cfn-lint-0.73.0-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.59.0",
noarch::cfn-lint-0.73.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.59.0",
noarch::cfn-lint-0.73.2-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.59.0",
noarch::cfn-lint-0.74.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.60.1",
noarch::cfn-lint-0.74.3-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.60.1",
noarch::cfn-lint-0.75.0-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.60.1",
noarch::cfn-lint-0.75.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.55.0",
+    "aws-sam-translator >=1.60.1",
noarch::cfn-lint-0.77.0-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.64.0",
noarch::cfn-lint-0.77.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.64.0",
noarch::cfn-lint-0.77.10-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.68.0",
noarch::cfn-lint-0.77.2-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.64.0",
noarch::cfn-lint-0.77.3-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.64.0",
noarch::cfn-lint-0.77.4-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.65.0",
noarch::cfn-lint-0.77.5-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.65.0",
noarch::cfn-lint-0.77.6-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.68.0",
noarch::cfn-lint-0.77.7-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.68.0",
noarch::cfn-lint-0.77.8-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.68.0",
noarch::cfn-lint-0.77.9-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.68.0",
noarch::cfn-lint-0.78.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.62.0",
+    "aws-sam-translator >=1.70.0",
noarch::cfn-lint-0.78.2-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.70.0",
+    "aws-sam-translator >=1.71.0",
noarch::cfn-lint-0.79.1-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.70.0",
+    "aws-sam-translator >=1.71.0",
noarch::cfn-lint-0.79.4-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.70.0",
+    "aws-sam-translator >=1.71.0",
noarch::cfn-lint-0.79.5-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.70.0",
+    "aws-sam-translator >=1.71.0",
noarch::cfn-lint-0.79.6-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.70.0",
+    "aws-sam-translator >=1.71.0",
noarch::cfn-lint-0.79.7-pyhd8ed1ab_0.conda
-    "aws-sam-translator >=1.70.0",
+    "aws-sam-translator >=1.71.0",

```

### CODE REVIEW

**Review by beckermr — APPROVED** [review]
Looks like we need some optional input data that could be referenced in the yaml patches maybe.

**Comment by maresb** [comment]
I haven't yet looked at the new YAML spec, but this patch seems much more extreme than anything else I've seen. (In order to generate the table I ran Grayskull, looping over the built versions, parsing the output yamls.)

But for most things it seems sufficient to just patch a handful of dependencies, so I'm saying that this case might be outside of the 99%. If we can already get 95% declarative that's awesome. :sunglasses:

**Comment by beckermr** [comment]
100% agreed! Thank you!

**Comment by maresb** [comment]
CI is green! :rocket:

**Pull request merged**
