### PR TITLE
connexion: Pin Flask < 2.3

### PR DESCRIPTION
**Pull request by jonashaag**
Checklist
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by jonashaag** [comment]
@xhochy does this look correct? First PR in this repo. I need to pin connexion 2.X to Flask < 2.3.

**Comment by jonashaag** [comment]
```
noarch::connexion-2.11.2-pyhd8ed1ab_1.tar.bz2
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
noarch::connexion-2.12.0-pyhd8ed1ab_0.tar.bz2
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
noarch::connexion-2.13.0-pyhd8ed1ab_0.tar.bz2
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
noarch::connexion-2.13.1-pyhd8ed1ab_0.tar.bz2
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
noarch::connexion-2.14.0-pyhd8ed1ab_0.tar.bz2
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
noarch::connexion-2.14.1-pyhd8ed1ab_0.tar.bz2
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
noarch::connexion-2.14.2-pyhd8ed1ab_0.conda
-    "flask >=1.0.4,<3",
+    "flask >=1.0.4,<2.3",
linux-64::ucx-1.14.0-h0aa22dc_1.conda
-    "cudatoolkit 10.2"
+    "cudatoolkit 10.2|10.2.*"
linux-64::ucx-1.14.0-h3484d09_1.conda
-    "cudatoolkit 11.1"
+    "cudatoolkit 11.1|11.1.*"
linux-64::ucx-1.14.0-h8d40d59_0.conda
-    "cudatoolkit 11.1"
+    "cudatoolkit 11.1|11.1.*"
linux-64::ucx-1.14.0-ha0ee010_0.conda
-    "cudatoolkit 11.0"
+    "cudatoolkit 11.0|11.0.*"
linux-64::ucx-1.14.0-hcb274ce_0.conda
-    "cudatoolkit 10.2"
+    "cudatoolkit 10.2|10.2.*"
linux-64::ucx-1.14.0-hd659935_1.conda
-    "cudatoolkit 11.0"
+    "cudatoolkit 11.0|11.0.*"
linux-aarch64::llvm-16.0.3-he38e8dc_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm-tools 16.0.3.*"
linux-aarch64::llvm-tools-16.0.3-h11d3cc5_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*"
linux-aarch64::llvmdev-16.0.3-hd8ae89b_0.conda
-  "version": "16.0.3"
+  "version": "16.0.3",
+  "constrains": [
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*",
+    "llvm-tools 16.0.3.*"
+  ]
linux-ppc64le::llvm-16.0.3-h97a5904_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm-tools 16.0.3.*"
linux-ppc64le::llvm-tools-16.0.3-hc314733_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*"
linux-ppc64le::llvmdev-16.0.3-hafd99fb_0.conda
-  "version": "16.0.3"
+  "version": "16.0.3",
+  "constrains": [
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*",
+    "llvm-tools 16.0.3.*"
+  ]
osx-arm64::llvm-16.0.3-h5856a0c_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm-tools 16.0.3.*"
osx-arm64::llvm-tools-16.0.3-hc12c677_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*"
osx-arm64::llvmdev-16.0.3-h09a3ea2_0.conda
-  "version": "16.0.3"
+  "version": "16.0.3",
+  "constrains": [
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*",
+    "llvm-tools 16.0.3.*"
+  ]
win-64::llvm-16.0.3-h38bddbe_0.conda
-  "version": "16.0.3"
+  "version": "16.0.3",
+  "constrains": [
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm-tools 16.0.3.*",
+    "llvmdev 16.0.3.*"
+  ]
win-64::llvm-tools-16.0.3-h2c25772_0.conda
-    "llvmdev   16.0.3"
+    "llvmdev   16.0.3",
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*"
win-64::llvmdev-16.0.3-h2c25772_0.conda
-  "version": "16.0.3"
+  "version": "16.0.3",
+  "constrains": [
+    "clang 16.0.3.*",
+    "clang-tools 16.0.3.*",
+    "llvm 16.0.3.*",
+    "llvm-tools 16.0.3.*"
+  ]
```

**Comment by xhochy** [comment]
FYI @conda-forge/connexion

**Comment by xhochy** [comment]
@jonashaag The next time, please ping the team of the feedstock and reference the PR that fixed the issue you are patching.

**Review by xylar — APPROVED** [review]
Thanks for the fix @jonashaag and for the ping @xhochy

**Comment by jonashaag** [comment]
Merge this?

**Pull request merged**
