### PR TITLE
fix libstdcxx requirement for libmamba 0.23.3

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
this is the result from `show_diff.py`:

```
linux-64::libmamba-0.23.3-hd8a31e3_1.tar.bz2
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py310hab0e683_1.tar.bz2
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py37h1ee4b26_1.tar.bz2
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py37h8c52fed_1.tar.bz2
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py38h923e62a_1.tar.bz2
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py39hd55135b_1.tar.bz2
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
```

cc @beckermr @isuruf

**Comment by wolfv** [comment]
We could use a timestamp based approach to fix other packages with this problem?

**Review by beckermr — COMMENTED** [review]
Do we need to do libgcc-ng too?

**Comment by wolfv** [comment]
@beckermr I think libgcc and libstdcxx are connected through some constraints.

**Comment by wolfv** [comment]
It looks like they are somehow connected through libgomp. But I can also add the same constraint to for libgcc-ng.

Here is the new diff 


```
linux-64::libmamba-0.23.3-hd8a31e3_1.tar.bz2
-    "libgcc-ng >=10.3.0",
+    "libgcc-ng >=12.1.0",
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py310hab0e683_1.tar.bz2
-    "libgcc-ng >=10.3.0",
+    "libgcc-ng >=12.1.0",
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py37h1ee4b26_1.tar.bz2
-    "libgcc-ng >=10.3.0",
+    "libgcc-ng >=12.1.0",
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py37h8c52fed_1.tar.bz2
-    "libgcc-ng >=10.3.0",
+    "libgcc-ng >=12.1.0",
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py38h923e62a_1.tar.bz2
-    "libgcc-ng >=10.3.0",
+    "libgcc-ng >=12.1.0",
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
linux-64::libmambapy-0.23.3-py39hd55135b_1.tar.bz2
-    "libgcc-ng >=10.3.0",
+    "libgcc-ng >=12.1.0",
-    "libstdcxx-ng >=10.3.0",
+    "libstdcxx-ng >=12.1.0",
```

**Review by beckermr — APPROVED** [review]

**Pull request merged**
