### PR TITLE
fix pillow constrains on previous napari releases

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
Comes from https://github.com/conda-forge/napari-feedstock/pull/33#discussion_r786978980

@conda-forge/napari 

```
python show_diff.py 
```

```diff
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::napari-0.3.7-py_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.3.8-py_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.0-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.10-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.11-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.12-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.2-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.3-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.4-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.5-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.6-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.7-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.8-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
noarch::napari-0.4.9-pyhd8ed1ab_0.tar.bz2
-    "pillow",
+    "pillow !=7.1.0,!=7.1.1",
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::h5utils-1.13.1-mpi_mpich_h88c8ee5_1012.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
linux-64::h5utils-1.13.1-mpi_mpich_ha777a55_1012.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::h5utils-1.13.1-mpi_mpich_h99bf298_1012.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
osx-64::h5utils-1.13.1-mpi_mpich_hab242fb_1012.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
```

**Comment by jaimergp** [comment]
Can anybody at @conda-forge/core tell me if I am doing this right? It looks ok but you never know :D

**Comment by beckermr** [comment]
LGTM!

**Comment by jaimergp** [comment]
Thanks!!

**Pull request merged**
