### PR TITLE
Mark tqdm-4.53.0-pyhd3deb0d_0.tar.bz2 for removal

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- part of the fix for https://github.com/conda-forge/tqdm-feedstock/issues/84 (also needs https://github.com/conda-forge/dagster-feedstock/pull/87)

cc @conda-forge/tqdm @jan-janssen

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by beckermr** [comment]
This PR needs to be sent to conda-forge/admin-requests. We want to make sure to add a broken label to this package in addition to removing it from the index.

**Comment by bollwyvl** [comment]
Thanks... i saw the "prefer yadda yadda" over there and came over here!

**Comment by beckermr** [comment]
The "prefer" part is for changing the repodata if possible, as opposed to a removal. The PR here would accomplish the same thing as a removal there. If you can patch the repodata without removing the package to fix the issue, then a PR here is good.

**Comment by bollwyvl** [comment]
Ah, yeah... this one definitely claims to be `0.0.0`, so i guess removal is
in order. PR created!

**Pull request closed without merging**
