### PR TITLE
REF remove binutils constraint

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
We don't need these since all of the incompatible versions of binutils at 2.34 exclude these versions of gcc.

**Comment by isuruf** [comment]
This should be reverted so that we could remove the ugly constraints in the recipe.

**Comment by beckermr** [comment]
I'm confused by your comment. Which recipe? How does it help?

**Comment by isuruf** [comment]
I want to remove https://github.com/conda-forge/binutils-feedstock/blob/master/recipe/meta.yaml#L42-L44

**Pull request merged**
