### PR TITLE
Require menuinst>=2 in conda-build 3.28.0 and 3.28.1

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist

* [X] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [ ] Ran `python show_diff.py` and posted the output as part of the PR.
* [X] Modifications won't affect packages built in the future. 

- https://github.com/AnacondaRecipes/repodata-hotfixes/pull/218

### CODE REVIEW

**Comment by xhochy** [comment]
@jaimergp Is this ready? I'm missing a diff here as an indicator, otherwise would be fine to merge.

**Comment by jaimergp** [comment]
Same, 3.28.0 is not patched. Is it because it's marked as broken? Anyway, ready for review and merge @xhochy

**Comment by jaimergp** [comment]
Ah, 3.28.1 is marked as broken now too, so maybe we don't need this after all. 3.28.2 should pin this adequately.

**Comment by hmaarrfk** [comment]
ok to close?

**Pull request closed without merging**
