### PR TITLE
Fix scipy pin for scikit-image v0.20.0 py<=3.9

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by xylar** [comment]
@valeriupredoi, please have a look.

@conda-forge/scikit-image, too.

**Comment by xylar** [comment]
This was fixed in https://github.com/conda-forge/scikit-image-feedstock/pull/102

**Review by valeriupredoi — APPROVED** [review]
looking good - many thanks @xylar :beer:

**Comment by valeriupredoi** [comment]
or @beckermr if you got a spare moment :beer:

**Comment by xylar** [comment]
@hmaarrfk, how about you?  Could you take a look?  I'm attempting to fix https://github.com/conda-forge/scikit-image-feedstock/pull/101, which is breaking `pip check` in CI on various of my packages.

**Comment by jaimergp** [comment]
I can take a look. Can you fix the conflicts? Thanks!

**Comment by ocefpaf** [comment]
> @ocefpaf, maybe you could have a look and merge this if you're happy?

Sorry, missed the ping. @jaimergp let me know if you got this one or if you need me to take a look at it.
PS: the pin and the diff looks LGTM.

**Comment by hmaarrfk** [comment]
Thanks

**Comment by xylar** [comment]
Thank you, @hmaarrfk!

**Comment by valeriupredoi** [comment]
Many thanks, guys 🍺

**Pull request merged**
