### PR TITLE
libiconv 1.15 and 1.16 are compatible

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/80

cc @scopatz

### CODE REVIEW

**Comment by beckermr** [comment]
Do we need to adjust the iconv run exports and pinning expression to pin only to the major version?

**Comment by isuruf** [comment]
No, because 1.17 might not be compatible.

**Comment by beckermr** [comment]
I see. So to summarize we'd like to have a system that does more fine-grained ABI compatibility so that we can avoid shipping a version every now and then.

**Comment by isuruf** [comment]
I didn't understand your comment. Summary is that for packages that doesn't use semver, we have to pin strict and loosen when we know that the versions are compatible.

**Comment by beckermr** [comment]
Right OFC. But I'd be nice to automate the loosening of the pins and if we did that, it should happen on a case-by-case basis for each new version.

**Comment by isuruf** [comment]
Sure. It would be nice to have.

Merge?

**Comment by beckermr** [comment]
ofc merge away!

**Comment by CJ-Wright** [comment]
Can we get that up as an issue though? Esp for the new spec `x.x` might not be very descriptive. It might be better to explicitly define the min and max compatible versions. This would cover most cases, at least until packages return to a previous ABI. In this case that would have been a change on the feedstock, when it got the version bump it would have bumped the max compatible version.

**Comment by isuruf** [comment]
>  In this case that would have been a change on the feedstock, when it got the version bump it would have bumped the max compatible version.

No, metadata in downstream packages need to be fixed.

**Pull request merged**
