### PR TITLE
Fix requirements for nglview 3.1.*

### PR DESCRIPTION
**Pull request by danielhollas**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

Backport of https://github.com/conda-forge/nglview-feedstock/pull/67 for nglview version >=3.1.x

Output from `python show_diff.py`
```diff
  noarch    
  noarch::nglview-3.1.0-pyh15ce09e_0.conda    
  noarch::nglview-3.1.0-pyh9b3bb53_0.conda    
  noarch::nglview-3.1.1-pyh9b3bb53_0.conda    
  noarch::nglview-3.1.2-pyh9b3bb53_0.conda    
  noarch::nglview-3.1.2-pyh15ce09e_0.conda    
  noarch::nglview-3.1.1-pyh15ce09e_0.conda    
-    "ipywidgets >=7",    
+    "ipywidgets >=8",    
+    "notebook >=7",
```

### CODE REVIEW

**Comment by danielhollas** [comment]
@hai-schrodinger can you take a look? This should backport changes to nglview requirements for v>3.1.x from https://github.com/conda-forge/nglview-feedstock/pull/67

**Comment by hainm** [comment]
> @hai-schrodinger can you take a look? This should backport changes to nglview requirements for v>3.1.x from [conda-forge/nglview-feedstock#67](https://github.com/conda-forge/nglview-feedstock/pull/67)

@danielhollas what is the meaning of backport here?
(Sorry I don't follow conda-forge for a while). I thought the [#67](https://github.com/conda-forge/nglview-feedstock/pull/67) will trigger new build for the same nglview version?

**Comment by danielhollas** [comment]
>I thought the https://github.com/conda-forge/nglview-feedstock/pull/67 will trigger new build for the same nglview version?

Indeed, version 3.1.2 should be fixed, but the same fix needs to be applied to versions 3.1.0 and 3.1.1. Those fixes could be done from the nglview-feedstock as well (by creating a separate branches) but this should be a simpler solution. 

I am also new to the conda-forge ecosystem and wasn't aware of this repo until few days ago; please see the discussion at https://github.com/conda-forge/jupyter_server-feedstock/pull/156

**Comment by hainm** [comment]
> > I thought the [conda-forge/nglview-feedstock#67](https://github.com/conda-forge/nglview-feedstock/pull/67) will trigger new build for the same nglview version?
> 
> Indeed, version 3.1.2 should be fixed, but the same fix needs to be applied to versions 3.1.0 and 3.1.1. Those fixes could be done from the nglview-feedstock as well (by creating a separate branches) but this should be a simpler solution.
> 
> I am also new to the conda-forge ecosystem and wasn't aware of this repo until few days ago; please see the discussion at [conda-forge/jupyter_server-feedstock#156](https://github.com/conda-forge/jupyter_server-feedstock/pull/156)

I see. Will merge after being green.

**Comment by danielhollas** [comment]
Hmm, the CI failed, but it seems like a transient network error?

```
2024-07-12T19:01:08.2090163Z Traceback (most recent call last):
2024-07-12T19:01:08.2090822Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/_build_env/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
2024-07-12T19:01:08.2097293Z     r = call_item.fn(*call_item.args, **call_item.kwargs)
2024-07-12T19:01:08.2097523Z         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-12T19:01:08.2097941Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/work/gen_patch_json.py", line 968, in _do_subdir
2024-07-12T19:01:08.2098249Z     instructions = _gen_patch_instructions(repodata, new_index, subdir)
2024-07-12T19:01:08.2098422Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-12T19:01:08.2099011Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/work/gen_patch_json.py", line 913, in _gen_patch_instructions
2024-07-12T19:01:08.2099489Z     _add_removals(instructions, subdir)
2024-07-12T19:01:08.2100121Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/work/gen_patch_json.py", line 893, in _add_removals
2024-07-12T19:01:08.2100552Z     r.raise_for_status()
2024-07-12T19:01:08.2101148Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/_build_env/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
2024-07-12T19:01:08.2101463Z     raise HTTPError(http_error_msg, response=self)
2024-07-12T19:01:08.2102019Z requests.exceptions.HTTPError: 524 Server Error:  for url: https://conda.anaconda.org/conda-forge/label/broken/linux-64/repodata.json
2024-07-12T19:01:08.2102410Z """
2024-07-12T19:01:08.2102662Z 
2024-07-12T19:01:08.2102826Z The above exception was the direct cause of the following exception:
2024-07-12T19:01:08.2102938Z 
2024-07-12T19:01:08.2103605Z Traceback (most recent call last):
2024-07-12T19:01:08.2103999Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/work/gen_patch_json.py", line 1012, in <module>
2024-07-12T19:01:08.2104311Z     sys.exit(main())
2024-07-12T19:01:08.2104472Z              ^^^^^^
2024-07-12T19:01:08.2104810Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/work/gen_patch_json.py", line 998, in main
2024-07-12T19:01:08.2105065Z     subdir, vals = fut.result()
2024-07-12T19:01:08.2105205Z                    ^^^^^^^^^^^^
2024-07-12T19:01:08.2105614Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/_build_env/lib/python3.11/concurrent/futures/_base.py", line 449, in result
2024-07-12T19:01:08.9293823Z     return self.__get_result()
2024-07-12T19:01:08.9294530Z            ^^^^^^^^^^^^^^^^^^^
2024-07-12T19:01:08.9295658Z   File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1720809820660/_build_env/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
2024-07-12T19:01:08.9442338Z     raise self._exception
2024-07-12T19:01:08.9444191Z requests.exceptions.HTTPError: 524 Server Error:  for url: https://conda.anaconda.org/conda-forge/label/broken/linux-64/repodata.json
```

I'll re-trigger the CI.

**Comment by danielhollas** [comment]
@conda-forge/conda-forge-repodata-patches ready for review

**Review by xhochy — APPROVED** [review]

**Pull request merged**
