### PR TITLE
Revert "add run_constrains on major compiler version for fenics-basix"

### PR DESCRIPTION
**Pull request by beckermr**
Reverts conda-forge/conda-forge-repodata-patches-feedstock#841

### CODE REVIEW

**Comment by beckermr** [comment]
cc @minrk

**Review by minrk — APPROVED** [review]

**Comment by beckermr** [comment]
Well there are two things here. The patch file is wrong, but also there appears to be an issue with changes in pydantic or something.

**Comment by beckermr** [comment]
The interesting bit is that the change wasn't generating valid json which means this is an upstream bug. Hopefully if we skip 2.9 it will get fixed eventually. It could be in json schema or pydantic.

**Comment by beckermr** [comment]
I am going to close this and submit two PRs that fix each thing instead of reverting.

**Comment by beckermr** [comment]
xref: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/846

Note there is no bug in the patch from Min as he correctly pointed out!

**Pull request closed without merging**
