### PR TITLE
Add Python 3.5+ requirement to numpydoc 1.0.0+

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/numpydoc-feedstock/issues/13

Also adding this change to the feedstock in PR ( https://github.com/conda-forge/numpydoc-feedstock/pull/14 ).

### CODE REVIEW

**Review by isuruf — CHANGES_REQUESTED** [review]
Can you add an upper bound on numpydoc version to 1.1.0 so that this patch is not added for future builds?

**Comment by jakirkham** [comment]
Sure added. Though it is worth noting the second condition would have caught that as well.

**Comment by isuruf** [comment]
Can you run `show_diff.py` and post the output?

**Comment by jakirkham** [comment]
Here's the relevant portion from the `noarch` repodata.

```diff
-    "python",
+    "python >=3.5",
noarch::numpydoc-0.9.0-py_0.tar.bz2
-    "python",
+    "python >=3.5",
noarch::numpydoc-0.9.1-py_0.tar.bz2
-    "python",
+    "python >=3.5",
noarch::numpydoc-0.9.2-py_0.tar.bz2
-    "python",
+    "python >=3.5",
noarch::numpydoc-1.0.0-pyh9f0ad1d_0.tar.bz2
-    "python",
+    "python >=3.5",
```

**Comment by isuruf** [comment]
That looks incorrect.

**Comment by jakirkham** [comment]
Yeah you're right. Should be fixed now

```diff
noarch::numpydoc-1.0.0-pyh9f0ad1d_0.tar.bz2
-    "python",
+    "python >=3.5",
noarch::numpydoc-1.1.0-pyh9f0ad1d_0.tar.bz2
-    "python",
+    "python >=3.5",
```

**Comment by jakirkham** [comment]
Is there anything else needed here?

**Comment by isuruf** [comment]
Thanks

**Comment by jakirkham** [comment]
Thanks for the review :)

**Pull request merged**
