### PR TITLE
Fix boost-cpp constraints for old Gazebo builds

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/gazebo-feedstock/issues/52 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
Please run the show diff script and post the output here so we can inspect it.

**Comment by traversaro** [comment]
Marking this as WIP as show_diff indicates that the condition based on timestamp does not seem to be working.

**Comment by wolfv** [comment]
I think pinning boost like this for any version of gazebo should be fine, right?

**Comment by beckermr** [comment]
I agree @wolfv but we do want the patches to only apply to packages from the past so that rebuilding them is a noop.

**Comment by traversaro** [comment]
> 
> 
> Marking this as WIP as show_diff indicates that the condition based on timestamp does not seem to be working.

It seems that _pin_stricter does now work with pins that only have a major then constraint on the version. In this case all the packages to fix have the constraint `boost-cpp >=1.71`, so we can just use `_replace_pin` instead.

**Comment by traversaro** [comment]
The show_diff output is: 
~~~
STraversaro@IITICUBLAP102 MINGW64 /c/src/conda-forge-repodata-patches-feedstock/recipe (patch-1)
$ ./show_diff.py
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::h5utils-1.13.1-mpi_mpich_hf4a456e_1010.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
linux-64::mpb-1.11.1-mpi_mpich_h7dcaacd_3.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
linux-64::pymeep-1.17.1-mpi_mpich_py36h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
linux-64::pymeep-1.17.1-mpi_mpich_py37h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
linux-64::pymeep-1.17.1-mpi_mpich_py38h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
linux-64::pymeep-1.17.1-mpi_mpich_py39h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
linux-aarch64::mpb-1.11.1-mpi_mpich_hcf527e8_3.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
linux-ppc64le::mpb-1.11.1-mpi_mpich_h7462faf_3.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::h5utils-1.13.1-mpi_mpich_h4a1c5b3_1010.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
osx-64::mpb-1.11.1-mpi_mpich_h6bcc534_3.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
osx-64::pymeep-1.17.1-mpi_mpich_py36h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
osx-64::pymeep-1.17.1-mpi_mpich_py37h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
osx-64::pymeep-1.17.1-mpi_mpich_py38h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
osx-64::pymeep-1.17.1-mpi_mpich_py39h1234567_1.tar.bz2
-    "mpich >=3.4,<3.5.0a0",
+    "mpich >=3.4,<4.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
win-64::gazebo-11.0.0-he9e614d_1.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-11.0.0-he9e614d_2.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-11.0.0-he9e614d_3.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.11.0-he9e614d_0.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.11.0-he9e614d_1.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.11.0-he9e614d_2.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.11.0-he9e614d_3.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.11.0-he9e614d_4.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.12.0-he9e614d_0.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
win-64::gazebo-9.12.0-he9e614d_1.tar.bz2
-    "boost-cpp >=1.71",
+    "boost-cpp >=1.71.0,<1.71.1.0a0",
~~~

The gazebo fixes are the intended ones, while the `mpich` seem unrelated but also appear if I just run `show_diff` on the master branch.

**Comment by beckermr** [comment]
The mpich fixes are a known issue with our patching. They are correct but it is not clear why we are still needing them to be applied.

**Review by beckermr — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @beckermr !

**Comment by isuruf** [comment]
> but it is not clear why we are still needing them to be applied.

? See https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/121#issuecomment-778862593

**Comment by beckermr** [comment]
Ahh yes! Thank you for the reminder. I forgot about that one!

**Pull request merged**
