### PR TITLE
Pin cryptography to versions compatible with pyopenssl

### PR DESCRIPTION
**Pull request by IzerOnadimQC**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

<details>
<summary>Diff output</summary>

```
$ python show_diff.py
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
win-32::pyopenssl-16.2.0-py27_0.tar.bz2
win-32::pyopenssl-16.2.0-py35_0.tar.bz2
win-32::pyopenssl-16.2.0-py36_0.tar.bz2
-    "cryptography >=1.3.4",
+    "cryptography >=1.3.4,<42.0.0a0",
win-32::pyopenssl-17.2.0-py27_0.tar.bz2
win-32::pyopenssl-17.2.0-py35_0.tar.bz2
win-32::pyopenssl-17.2.0-py36_0.tar.bz2
-    "cryptography >=1.9",
+    "cryptography >=1.9,<42.0.0a0",
win-32::pyopenssl-16.0.0-py27_0.tar.bz2
win-32::pyopenssl-16.0.0-py34_0.tar.bz2
win-32::pyopenssl-16.0.0-py35_0.tar.bz2
-    "cryptography >=1.3",
+    "cryptography >=1.3,<42.0.0a0",
win-32::pyopenssl-17.5.0-py27_1.tar.bz2
win-32::pyopenssl-17.5.0-py35_1.tar.bz2
win-32::pyopenssl-17.5.0-py36_1.tar.bz2
-    "cryptography >=2.1.4",
+    "cryptography >=2.1.4,<42.0.0a0",
================================================================================
================================================================================
linux-ppc64le
linux-ppc64le::pyopenssl-19.0.0-py27_0.tar.bz2
linux-ppc64le::pyopenssl-19.0.0-py36_0.tar.bz2
linux-ppc64le::pyopenssl-19.0.0-py37_0.tar.bz2
linux-ppc64le::pyopenssl-19.0.0-py38_0.tar.bz2
-    "cryptography >=2.2.1",
+    "cryptography >=2.2.1,<42.0.0a0",
linux-ppc64le::pyopenssl-19.1.0-py36_0.tar.bz2
linux-ppc64le::pyopenssl-19.1.0-py37_0.tar.bz2
linux-ppc64le::pyopenssl-19.1.0-py38_0.tar.bz2
-    "cryptography >=2.8",
+    "cryptography >=2.8,<42.0.0a0",
================================================================================
================================================================================
linux-aarch64
linux-aarch64::pyopenssl-19.0.0-py27_0.tar.bz2
linux-aarch64::pyopenssl-19.0.0-py36_0.tar.bz2
linux-aarch64::pyopenssl-19.0.0-py37_0.tar.bz2
linux-aarch64::pyopenssl-19.0.0-py38_0.tar.bz2
-    "cryptography >=2.2.1",
+    "cryptography >=2.2.1,<42.0.0a0",
linux-aarch64::pyopenssl-19.1.0-py36_0.tar.bz2
linux-aarch64::pyopenssl-19.1.0-py37_0.tar.bz2
linux-aarch64::pyopenssl-19.1.0-py38_0.tar.bz2
-    "cryptography >=2.8",
+    "cryptography >=2.8,<42.0.0a0",
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
noarch
noarch::pyopenssl-21.0.0-pyhd8ed1ab_0.tar.bz2
-    "cryptography >=3.3",
+    "cryptography >=3.3,<42.0.0a0",
noarch::pyopenssl-19.1.0-py_1.tar.bz2
-    "cryptography >=2.8",
+    "cryptography >=2.8,<42.0.0a0",
noarch::pyopenssl-20.0.0-pyhd8ed1ab_0.tar.bz2
noarch::pyopenssl-20.0.1-pyhd8ed1ab_0.tar.bz2
-    "cryptography >=3.2",
+    "cryptography >=3.2,<42.0.0a0",
noarch::bitstring-4.1.0-pyhd8ed1ab_0.conda
-    "bitarray >=2.8.0,<3",
+    "bitarray >=2.8.0",
================================================================================
================================================================================
win-64
win-64::pyopenssl-17.5.0-py27_1.tar.bz2
win-64::pyopenssl-17.5.0-py35_1.tar.bz2
win-64::pyopenssl-17.5.0-py36_1.tar.bz2
-    "cryptography >=2.1.4",
+    "cryptography >=2.1.4,<42.0.0a0",
win-64::pyopenssl-16.0.0-py27_0.tar.bz2
win-64::pyopenssl-16.0.0-py34_0.tar.bz2
win-64::pyopenssl-16.0.0-py35_0.tar.bz2
-    "cryptography >=1.3",
+    "cryptography >=1.3,<42.0.0a0",
win-64::pyopenssl-18.0.0-py27_0.tar.bz2
win-64::pyopenssl-18.0.0-py27_1000.tar.bz2
win-64::pyopenssl-18.0.0-py35_0.tar.bz2
win-64::pyopenssl-18.0.0-py36_0.tar.bz2
win-64::pyopenssl-18.0.0-py36_1000.tar.bz2
win-64::pyopenssl-18.0.0-py37_0.tar.bz2
win-64::pyopenssl-18.0.0-py37_1000.tar.bz2
win-64::pyopenssl-19.0.0-py27_0.tar.bz2
win-64::pyopenssl-19.0.0-py36_0.tar.bz2
win-64::pyopenssl-19.0.0-py37_0.tar.bz2
win-64::pyopenssl-19.0.0-py38_0.tar.bz2
-    "cryptography >=2.2.1",
+    "cryptography >=2.2.1,<42.0.0a0",
win-64::pyopenssl-17.2.0-py27_0.tar.bz2
win-64::pyopenssl-17.2.0-py35_0.tar.bz2
win-64::pyopenssl-17.2.0-py36_0.tar.bz2
-    "cryptography >=1.9",
+    "cryptography >=1.9,<42.0.0a0",
win-64::pyopenssl-16.2.0-py27_0.tar.bz2
win-64::pyopenssl-16.2.0-py35_0.tar.bz2
win-64::pyopenssl-16.2.0-py36_0.tar.bz2
-    "cryptography >=1.3.4",
+    "cryptography >=1.3.4,<42.0.0a0",
win-64::pyopenssl-19.1.0-py27_0.tar.bz2
win-64::pyopenssl-19.1.0-py36_0.tar.bz2
win-64::pyopenssl-19.1.0-py37_0.tar.bz2
win-64::pyopenssl-19.1.0-py38_0.tar.bz2
-    "cryptography >=2.8",
+    "cryptography >=2.8,<42.0.0a0",
================================================================================
================================================================================
osx-64
osx-64::pyopenssl-17.2.0-py27_0.tar.bz2
osx-64::pyopenssl-17.2.0-py35_0.tar.bz2
osx-64::pyopenssl-17.2.0-py36_0.tar.bz2
osx-64::pyopenssl-17.4.0-py27_0.tar.bz2
osx-64::pyopenssl-17.4.0-py35_0.tar.bz2
osx-64::pyopenssl-17.4.0-py36_0.tar.bz2
-    "cryptography >=1.9",
+    "cryptography >=1.9,<42.0.0a0",
osx-64::pyopenssl-16.2.0-py27_0.tar.bz2
osx-64::pyopenssl-16.2.0-py35_0.tar.bz2
osx-64::pyopenssl-16.2.0-py36_0.tar.bz2
-    "cryptography >=1.3.4",
+    "cryptography >=1.3.4,<42.0.0a0",
osx-64::pyopenssl-19.1.0-py27_0.tar.bz2
osx-64::pyopenssl-19.1.0-py36_0.tar.bz2
osx-64::pyopenssl-19.1.0-py37_0.tar.bz2
osx-64::pyopenssl-19.1.0-py38_0.tar.bz2
-    "cryptography >=2.8",
+    "cryptography >=2.8,<42.0.0a0",
osx-64::pyopenssl-18.0.0-py27_0.tar.bz2
osx-64::pyopenssl-18.0.0-py27_1000.tar.bz2
osx-64::pyopenssl-18.0.0-py35_0.tar.bz2
osx-64::pyopenssl-18.0.0-py36_0.tar.bz2
osx-64::pyopenssl-18.0.0-py36_1000.tar.bz2
osx-64::pyopenssl-18.0.0-py37_0.tar.bz2
osx-64::pyopenssl-18.0.0-py37_1000.tar.bz2
osx-64::pyopenssl-19.0.0-py27_0.tar.bz2
osx-64::pyopenssl-19.0.0-py36_0.tar.bz2
osx-64::pyopenssl-19.0.0-py37_0.tar.bz2
osx-64::pyopenssl-19.0.0-py38_0.tar.bz2
-    "cryptography >=2.2.1",
+    "cryptography >=2.2.1,<42.0.0a0",
osx-64::pyopenssl-17.5.0-py27_1.tar.bz2
osx-64::pyopenssl-17.5.0-py35_1.tar.bz2
osx-64::pyopenssl-17.5.0-py36_1.tar.bz2
-    "cryptography >=2.1.4",
+    "cryptography >=2.1.4,<42.0.0a0",
osx-64::pyopenssl-16.0.0-py27_0.tar.bz2
osx-64::pyopenssl-16.0.0-py34_0.tar.bz2
osx-64::pyopenssl-16.0.0-py35_0.tar.bz2
osx-64::pyopenssl-16.0.0-py36_0.tar.bz2
-    "cryptography >=1.3",
+    "cryptography >=1.3,<42.0.0a0",
================================================================================
================================================================================
linux-64
linux-64::pyopenssl-17.2.0-py27_0.tar.bz2
linux-64::pyopenssl-17.2.0-py35_0.tar.bz2
linux-64::pyopenssl-17.2.0-py36_0.tar.bz2
linux-64::pyopenssl-17.4.0-py27_0.tar.bz2
linux-64::pyopenssl-17.4.0-py35_0.tar.bz2
linux-64::pyopenssl-17.4.0-py36_0.tar.bz2
-    "cryptography >=1.9",
+    "cryptography >=1.9,<42.0.0a0",
linux-64::pyopenssl-18.0.0-py27_0.tar.bz2
linux-64::pyopenssl-18.0.0-py27_1000.tar.bz2
linux-64::pyopenssl-18.0.0-py35_0.tar.bz2
linux-64::pyopenssl-18.0.0-py36_0.tar.bz2
linux-64::pyopenssl-18.0.0-py36_1000.tar.bz2
linux-64::pyopenssl-18.0.0-py37_0.tar.bz2
linux-64::pyopenssl-18.0.0-py37_1000.tar.bz2
linux-64::pyopenssl-19.0.0-py27_0.tar.bz2
linux-64::pyopenssl-19.0.0-py36_0.tar.bz2
linux-64::pyopenssl-19.0.0-py37_0.tar.bz2
linux-64::pyopenssl-19.0.0-py38_0.tar.bz2
-    "cryptography >=2.2.1",
+    "cryptography >=2.2.1,<42.0.0a0",
linux-64::pyopenssl-16.0.0-py27_0.tar.bz2
linux-64::pyopenssl-16.0.0-py34_0.tar.bz2
linux-64::pyopenssl-16.0.0-py35_0.tar.bz2
linux-64::pyopenssl-16.0.0-py36_0.tar.bz2
-    "cryptography >=1.3",
+    "cryptography >=1.3,<42.0.0a0",
linux-64::pyopenssl-19.1.0-py27_0.tar.bz2
linux-64::pyopenssl-19.1.0-py36_0.tar.bz2
linux-64::pyopenssl-19.1.0-py37_0.tar.bz2
linux-64::pyopenssl-19.1.0-py38_0.tar.bz2
-    "cryptography >=2.8",
+    "cryptography >=2.8,<42.0.0a0",
linux-64::pyopenssl-17.5.0-py27_1.tar.bz2
linux-64::pyopenssl-17.5.0-py35_1.tar.bz2
linux-64::pyopenssl-17.5.0-py36_1.tar.bz2
-    "cryptography >=2.1.4",
+    "cryptography >=2.1.4,<42.0.0a0",
linux-64::pyopenssl-16.2.0-py27_0.tar.bz2
linux-64::pyopenssl-16.2.0-py35_0.tar.bz2
linux-64::pyopenssl-16.2.0-py36_0.tar.bz2
-    "cryptography >=1.3.4",
+    "cryptography >=1.3.4,<42.0.0a0",
```
</details>

### CODE REVIEW

**Comment by maresb** [comment]
I should have checked more carefully. I opened a duplicate in #918. Either should work. I certainly won't be offended if you close mine. I do the tightening slightly differently, as detailed in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/918#issuecomment-2513071383.

It would be great to get one of these merged soon, since I suspect this may be causing some fairly widespread breakage.

**Comment by IzerOnadimQC** [comment]
> I should have checked more carefully. I opened a duplicate in #918. Either should work. I certainly won't be offended if you close mine. I do the tightening slightly differently, as detailed in [#918 (comment)](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/918#issuecomment-2513071383).

I'm not overly opinionated on which approach we take - AFAICT your approach would also fix the issue and does not seem overly constraining. The one thing I would say about your approach is that it could probably be made simpler by removing the existing [version constraint](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/918/files#diff-f4371d892cf8798694e2a9bc5a14a944c65af3a32e9412dcf1612f1020ea8425R14), and just converting your `version_lt` to a version `version_le`, which, if I'm understanding correctly, would cover both cases.

> It would be great to get one of these merged soon, since I suspect this may be causing some fairly widespread breakage.

Agreed. Could a member of @conda-forge/core please approve and merge either one?

**Comment by jakirkham** [comment]
@h-vetinari could you please take a look at this PR and PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/918 )?

**Review by h-vetinari — APPROVED** [review]
LGTM

**Comment by maresb** [comment]
After sleeping on this, I think that my pins are slightly better because they are monotone. (With this version there is a very slight risk that the solver finds a local optimum with pyopenssl 21.0.0 and cryptography 41 since pyopenssl 22.0.0 requires cryptography <39.)

I think the comments here are more informative, so I'm going to copy those to my branch in #918.

**Pull request closed without merging**
