### PR TITLE
BUGZ right min for libgfrotran

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
OK @scopatz @chrisburr @conda-forge/core 

Thank you for bearing with me on my journey of bugs. 

We should add 3.0.1 to our channels for libgfortran as well.

**Comment by scopatz** [comment]
Thanks!

**Comment by beckermr** [comment]
Let's hope this works! I'd love to one day have test channels that we can stage changes into instead of testing everything live. OTOH YOLO!

**Comment by jakirkham** [comment]
> I'd love to one day have test channels that we can stage changes into instead of testing everything live.

Have you seen issue ( https://github.com/conda-forge/conda-forge.github.io/issues/204 )?

**Pull request merged**
