### PR TITLE
pin ruff in python-lsp-ruff

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

References:
- finishes https://github.com/conda-forge/python-lsp-ruff-feedstock/pull/10

```diff
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
linux-ppc64le
linux-ppc64le::llvm-17.0.3-h381f82a_0.conda
+    "clang 17.0.3.*",
+    "clang-tools 17.0.3.*",
+    "llvm-tools 17.0.3.*",
linux-ppc64le::llvm-tools-17.0.3-h8d57982_0.conda
+    "clang 17.0.3.*",
+    "clang-tools 17.0.3.*",
+    "llvm 17.0.3.*",
linux-ppc64le::llvmdev-17.0.3-h8d57982_0.conda
+  "constrains": [
+    "clang 17.0.3.*",
+    "clang-tools 17.0.3.*",
+    "llvm 17.0.3.*",
+    "llvm-tools 17.0.3.*"
+  ],
================================================================================
================================================================================
linux-aarch64
linux-aarch64::llvm-17.0.3-h5271726_0.conda
+    "clang 17.0.3.*",
+    "clang-tools 17.0.3.*",
+    "llvm-tools 17.0.3.*",
linux-aarch64::llvm-tools-17.0.3-h70e38ee_0.conda
+    "clang 17.0.3.*",
+    "clang-tools 17.0.3.*",
+    "llvm 17.0.3.*",
linux-aarch64::llvmdev-17.0.3-h70e38ee_0.conda
+  "constrains": [
+    "clang 17.0.3.*",
+    "clang-tools 17.0.3.*",
+    "llvm 17.0.3.*",
+    "llvm-tools 17.0.3.*"
+  ],
================================================================================
================================================================================
noarch
noarch::python-lsp-ruff-1.2.0-pyhd8ed1ab_0.conda
-    "ruff >=0.0.192"
+    "ruff >=0.0.192,<0.1.0a0"
noarch::python-lsp-ruff-1.3.0-pyhd8ed1ab_0.conda
-    "ruff >=0.0.260"
+    "ruff >=0.0.260,<0.1.0a0"
noarch::python-lsp-ruff-1.4.0-pyhd8ed1ab_1.conda
noarch::python-lsp-ruff-1.4.0-pyhd8ed1ab_0.conda
noarch::python-lsp-ruff-1.5.0-pyhd8ed1ab_0.conda
-    "ruff >=0.0.260",
+    "ruff >=0.0.260,<0.1.0a0",
noarch::python-lsp-ruff-1.5.1-pyhd8ed1ab_0.conda
noarch::python-lsp-ruff-1.5.2-pyhd8ed1ab_0.conda
-    "ruff >=0.0.267",
+    "ruff >=0.0.267,<0.1.0a0",
================================================================================
================================================================================
win-64
================================================================================
================================================================================
osx-64
================================================================================
================================================================================
linux-64

```

### CODE REVIEW

**Comment by bollwyvl** [comment]
Presumably the `llvm` ones are just some kind of race condition in the automation...

**Comment by bollwyvl** [comment]
While I'm watching this stuff scroll by about llvm: might whoever looks at this have any ideas about:

```
Failed to find libFuzzer archive in search path 
Failed to find libFuzzer; set either $CLANG_BIN to point to your Clang binary, or $LIBFUZZER_LIB to point directly to your libFuzzer .a file. If needed, download and build the latest version of Clang:
    git clone --depth=1 https://github.com/llvm/llvm-project.git
    cd llvm-project
    cmake -DLLVM_ENABLE_PROJECTS='clang;compiler-rt' -G "Unix Makefiles" -S llvm -B build
    NPROC=$(sysctl -n hw.logicalcpu 2>/dev/null || nproc)
    cmake --build build --parallel $NPROC # This step is very slow.
Then, set $CLANG_BIN="$(pwd)/bin/clang" and run pip again.
You should use this same Clang for building any Python extensions you plan to fuzz.
```

https://github.com/conda-forge/atheris-feedstock/pull/14#issuecomment-1699121776

**Comment by bollwyvl** [comment]
@conda-forge/conda-forge-repodata-patches ready for review

**Comment by bollwyvl** [comment]
@conda-forge/conda-forge-repodata-patches @conda-forge/core we actually have a proper fix in now so this is... less important:

https://github.com/conda-forge/python-lsp-ruff-feedstock/pull/12

(but probably still useful to get in to be accurate)

**Comment by beckermr** [comment]
llvm is a patch that is not bound in our system. I made an issue/PR about moving it to the feedstock but nobody took any action on it.

**Comment by h-vetinari** [comment]
> but nobody took any action on it.

Yes I did, but no-one reviewed that PR

**Comment by bollwyvl** [comment]
thanks all!

**Comment by beckermr** [comment]
Ahhhh sorry @h-vetinari ! I can review it but I'm not qualified to do so tbh.

**Pull request merged**
