### PR TITLE
Let `nvidia-ml-py` and `pynvml` `12.*` coexist

### PR DESCRIPTION
**Pull request by jakirkham**
Beginning with `pynvml` version `12.0.0`, the `pynvml` library and package now depend on `nvidia-ml-py` for core functionality and merely provide a few extras on top of `nvidia-ml-py`. Given this, these two packages no longer clobber each other and instead `nvidia-ml-py` needs to be coinstallable with `pynvml`. Changes were made to both feedstocks to support this (as referenced below). This repodata patch extends this to `nvidia-ml-py` version `12.*`.

References:
* https://github.com/gpuopenanalytics/pynvml/pull/57
* https://github.com/conda-forge/pynvml-feedstock/pull/18
* https://github.com/conda-forge/nvidia-ml-py-feedstock/pull/24

<hr>

Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/nvidia-ml-py @conda-forge/pynvml (for awareness)

**Comment by jakirkham** [comment]
Here is the repodata patch diff [from CI]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/actions/runs/12402777594/job/34625000122?pr=932#step:3:1114 ):

```diff
noarch::nvidia-ml-py-12.555.43-pyhd8ed1ab_0.conda
noarch::nvidia-ml-py-12.535.77-pyhd8ed1ab_0.conda
noarch::nvidia-ml-py-12.535.108-pyhd8ed1ab_0.conda
noarch::nvidia-ml-py-12.560.30-pyhd8ed1ab_0.conda
noarch::nvidia-ml-py-12.550.52-pyhd8ed1ab_0.conda
noarch::nvidia-ml-py-12.535.133-pyhd8ed1ab_0.conda
-    "pynvml ==9999999999"
+    "pynvml ~=12.0"
```

**Comment by hmaarrfk** [comment]
what does ~=12.0 mean?

**Comment by jakirkham** [comment]
This is equivalent to `nvidia-ml-py >=12.0,<13.0a`

More details in the [package match specification docs]( https://docs.conda.io/projects/conda-build/en/stable/resources/package-spec.html#package-match-specifications )

xref: https://github.com/conda-forge/pynvml-feedstock/pull/18#discussion_r1889677187

**Comment by jakirkham** [comment]
@conda-forge-admin , please relint

(looks like [the linter errored during installation]( https://github.com/conda-forge/conda-forge-webservices/actions/runs/12402777903/job/34625000458#step:3:415 ))

**Comment by hmaarrfk** [comment]
LGTM

**Review by kkraus14 — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Mark and Keith! 🙏

**Comment by jaimergp** [comment]
I remember we were patching =~ out because it would break old conda versions. Also mamba v2 seems to have some trouble with it. Might be safer to use the equivalent `>=x.y,x.*`.

**Comment by jakirkham** [comment]
How old of a version?

**Pull request merged**
