### PR TITLE
Fix nvidia-apex constrains

### PR DESCRIPTION
**Pull request by JanuszL**
- the nvidia-apex uses unsupported syntax in the constraints definition.
  This PR fixes that. See https://github.com/conda-forge/nvidia-apex-feedstock/issues/29

Checklist
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
```+ python show_diff.py
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
linux-64::nvidia-apex-22.03-cuda102py310hce0d3a8_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda102py38h73d78a8_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda102py39h4af2978_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda110py310h7cf977e_0.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda110py38hf5749dc_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda110py39h31ddb46_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda111py310h11f0b9a_0.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda111py38h7ba73a8_0.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda111py39h2dd2c40_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py310h6ec7b7f_0.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py310hb11405b_1.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py311h6c9afd8_1.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py38hd717573_1.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py38hdf64721_0.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "pytorch =*=cuda*"
+    "pytorch =*=cuda*",
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py39h83a068c_0.conda
-    "nvidia-apex-proc =*=cpu",
-    "nvidia-apex-proc =*=cuda|=*=gpu"
+    "nvidia-apex-proc =*=cuda"
linux-64::nvidia-apex-22.03-cuda112py39h955c134_1.conda
-    "nvidia-apex-proc =*=cuda|=*=gpu",
-    "nvidia-apex-proc =*=cpu"
+    "nvidia-apex-proc =*=cuda"
+ exit 0
```
* [x] Modifications are bound by `python -c "import time; print(f'{time.time():.0f}000')"`

Fixes https://github.com/conda-forge/nvidia-apex-feedstock/issues/29
Closes https://github.com/conda-forge/admin-requests/pull/674

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @jaimergp @h-vetinari 

cc @conda-forge/nvidia-apex

**Comment by jakirkham** [comment]
cc @rphel @mfansler

**Review by h-vetinari — APPROVED** [review]
LGTM, thanks for tackling this!

**Comment by jakirkham** [comment]
Planning on merging EOD Monday if no comments

**Comment by jakirkham** [comment]
Thanks Janusz! 🙏

**Pull request merged**
