### PR TITLE
remove optional dependencies from ray constraint in awswrangler

### PR DESCRIPTION
**Pull request by baszalmstra**
Checklist

* [ ] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

See: https://github.com/conda-forge/awswrangler-feedstock/pull/126

```
================================================================================
================================================================================
noarch
noarch::awswrangler-3.0.0-pyhd8ed1ab_0.conda
noarch::awswrangler-3.1.1-pyhd8ed1ab_0.conda
noarch::awswrangler-3.2.0-pyhd8ed1ab_0.conda
noarch::awswrangler-3.2.1-pyhd8ed1ab_0.conda
-    "ray[default,data] >=2.0.0,<2.4.0",
+    "ray >=2.0.0,<2.4.0",
noarch::awswrangler-3.4.0-pyhd8ed1ab_0.conda
noarch::awswrangler-3.3.0-pyhd8ed1ab_0.conda
noarch::awswrangler-3.4.1-pyhd8ed1ab_0.conda
noarch::awswrangler-3.4.2-pyhd8ed1ab_0.conda
-    "ray[default,data] >=2.0.0,<2.7.0",
+    "ray >=2.0.0,<2.7.0",
noarch::awswrangler-3.7.3-pyhd8ed1ab_0.conda
noarch::awswrangler-3.7.2-pyhd8ed1ab_0.conda
noarch::awswrangler-3.7.0-pyhd8ed1ab_0.conda
noarch::awswrangler-3.5.1-pyhd8ed1ab_0.conda
noarch::awswrangler-3.7.1-pyhd8ed1ab_0.conda
noarch::awswrangler-3.6.0-pyhd8ed1ab_0.conda
noarch::awswrangler-3.5.2-pyhd8ed1ab_0.conda
noarch::awswrangler-3.5.0-pyhd8ed1ab_0.conda
-    "ray[default,data] >=2.9.0,<3.0.0",
+    "ray >=2.9.0,<3.0.0",
```

### CODE REVIEW

**Comment by hmaarrfk** [comment]
how did the tests pass for that feedstock? that syntax isn't entirely correct for conda(-forge).

**Comment by hmaarrfk** [comment]
would it be fixed by you release a new build?

Sometimes that just easier.... patching creates weirdness if people already have the package downloaded.

**Comment by baszalmstra** [comment]
Unfortunately not because the solver tries to parse the repodata of the old packages. The way forward is to fix this both in new and historical data.

**Comment by baszalmstra** [comment]
@hmaarrfk The feedstock has been updated to fix any future versions. This patch is now ready for review!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
