### PR TITLE
Hotfix `panel` packages to constrain `setuptools`

### PR DESCRIPTION
**Pull request by jakirkham**
Hotfixes `panel` packages to require & constrain `setuptools` ( https://github.com/conda-forge/panel-feedstock/pull/48 )

cc @conda-forge/panel

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Here's the diff from this patch:

<details>

```
$ python show_diff.py 
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::panel-0.1.2-0.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.1.3-0.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.10.0-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.10.1-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.10.1-pyhd8ed1ab_1.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.10.2-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.10.3-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.11.0-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.11.1-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.11.2-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.11.3-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.12.0-pyhd8ed1ab_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.12.1-pyhd8ed1ab_0.tar.bz2
-    "tqdm >=4.48.0"
+    "tqdm >=4.48.0",
+    "setuptools >=42,<61"
noarch::panel-0.12.3-pyhd8ed1ab_0.tar.bz2
-    "tqdm >=4.48.0"
+    "tqdm >=4.48.0",
+    "setuptools >=42,<61"
noarch::panel-0.12.4-pyhd8ed1ab_0.tar.bz2
-    "tqdm >=4.48.0"
+    "tqdm >=4.48.0",
+    "setuptools >=42,<61"
noarch::panel-0.12.6-pyhd8ed1ab_0.tar.bz2
-    "tqdm >=4.48.0"
+    "tqdm >=4.48.0",
+    "setuptools >=42,<61"
noarch::panel-0.3.1-0.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.4.0-0.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.4.0-1.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.5.1-0.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.5.1-1.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.5.1-h24bf2e0_2.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.5.1-h39e3cac_2.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.6.0-1.tar.bz2
-    "pyviz_comms >=0.7.2"
+    "pyviz_comms >=0.7.2",
+    "setuptools >=42,<61"
noarch::panel-0.6.0-h5ca1d4c_0.tar.bz2
-    "testpath <0.4"
+    "testpath <0.4",
+    "setuptools >=42,<61"
noarch::panel-0.6.2-0.tar.bz2
-    "pyviz_comms >=0.7.2"
+    "pyviz_comms >=0.7.2",
+    "setuptools >=42,<61"
noarch::panel-0.6.3-0.tar.bz2
-    "pyviz_comms >=0.7.2"
+    "pyviz_comms >=0.7.2",
+    "setuptools >=42,<61"
noarch::panel-0.6.4-0.tar.bz2
-    "pyviz_comms >=0.7.2"
+    "pyviz_comms >=0.7.2",
+    "setuptools >=42,<61"
noarch::panel-0.7.0-0.tar.bz2
-    "pyviz_comms >=0.7.2"
+    "pyviz_comms >=0.7.2",
+    "setuptools >=42,<61"
noarch::panel-0.8.0-0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.8.1-pyh9f0ad1d_1.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.1-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.2-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.3-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.5-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.5-py_1.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.6-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
noarch::panel-0.9.7-py_0.tar.bz2
-    "tqdm"
+    "tqdm",
+    "setuptools >=42,<61"
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::llvm-14.0.0-h32600fe_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm-tools 14.0.0.*"
linux-64::llvm-tools-14.0.0-he0ac6c6_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*"
linux-64::llvmdev-14.0.0-he0ac6c6_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*",
+    "llvm-tools 14.0.0.*"
+  ]
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
linux-aarch64::llvm-14.0.0-h40ce709_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm-tools 14.0.0.*"
linux-aarch64::llvm-tools-14.0.0-hb2805f8_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*"
linux-aarch64::llvmdev-14.0.0-hb2805f8_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*",
+    "llvm-tools 14.0.0.*"
+  ]
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
linux-ppc64le::llvm-14.0.0-h12068cf_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm-tools 14.0.0.*"
linux-ppc64le::llvm-tools-14.0.0-h3b69f5b_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*"
linux-ppc64le::llvmdev-14.0.0-h3b69f5b_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*",
+    "llvm-tools 14.0.0.*"
+  ]
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::llvm-14.0.0-h9d075a6_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm-tools 14.0.0.*"
osx-64::llvm-tools-14.0.0-h89d5e19_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*"
osx-64::llvmdev-14.0.0-h89d5e19_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*",
+    "llvm-tools 14.0.0.*"
+  ]
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
osx-arm64::llvm-14.0.0-h95d0606_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm-tools 14.0.0.*"
osx-arm64::llvm-tools-14.0.0-hfd59cb2_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*"
osx-arm64::llvmdev-14.0.0-hfd59cb2_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*",
+    "llvm-tools 14.0.0.*"
+  ]
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
win-64::llvm-14.0.0-h6fda50d_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm-tools 14.0.0.*",
+    "llvmdev 14.0.0.*"
+  ]
win-64::llvm-tools-14.0.0-hf00eed6_0.tar.bz2
-    "llvmdev   14.0.0"
+    "llvmdev   14.0.0",
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*"
win-64::llvmdev-14.0.0-h97333cc_0.tar.bz2
-  "version": "14.0.0"
+  "version": "14.0.0",
+  "constrains": [
+    "clang 14.0.0.*",
+    "clang-tools 14.0.0.*",
+    "llvm 14.0.0.*",
+    "llvm-tools 14.0.0.*"
+  ]
```

</details>

**Comment by hmaarrfk** [comment]
Setup tools has been breaking many things :(

**Comment by jakirkham** [comment]
Yeah 😞 

It may be possible to fix this with `panel` in the future ( https://github.com/holoviz/panel/issues/3282 ). Though for now it seems pinning may be the right approach.

**Comment by jakirkham** [comment]
@philippjfr @maximlt, would be good to hear your thoughts here as well 🙂

**Comment by philippjfr** [comment]
I'm not sure this is actually needed. The issue wasn't actually down to the runtime usage of Setuptools and the pin was probably unnecessary. @maximlt can correct though.

**Comment by maximlt** [comment]
Yes the issue we saw was related to a dev package that we use - `pyctdev` - that wasn't compatible with the latest version of setuptools and caused Holoviz' CI runs to fail. The setuptools pins added to panel were a workaround (it was also urgent to release a new version of panel after the latest versions of jinja2 broke it!), shortly after a new release of pyctdev was made with support for the latest setuptools.

Except if you've seen another error or warning we haven't yet spotted @jakirkham ?

**Comment by jakirkham** [comment]
Ah ok. We have seen other broad impact issues with the newer `setuptools`. That said, if you are not running into those (as sounds to be the case), think we can can skip this.

**Pull request closed without merging**
