### PR TITLE
add support for 'packages.conda' section hotfixing

### PR DESCRIPTION
**Pull request by msarahan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
Thank you for the PR! I think I know a way to improve the diff. I'm nervous to merge now since it is hard to verify.

**Comment by beckermr** [comment]
OK @msarahan. That diff is a lot better!

Can you double check I didn't mess anything up?

**Comment by msarahan** [comment]
great idea on reducing the diff. A good way to test this is to ask Anaconda to convert a few files that you know will undergo some kind of patching if things here work correctly. Once they convert any files, the packages.conda section should show up the next time they run `conda index`. Perhaps also throw in a few other packages that don't need patching, just for reference.

Once you have conda-forge's repodata.json with at least a few entries in packages.conda, you should be able to simply build this package and verify that the patch files contained within have the expected patch instructions.

**Comment by beckermr** [comment]
It turns out our show_diff.py script is calling the right indexing functions from conda build locally. Thus I have enables that test after fixing the script. It passed locally and so we should be good to merge. 

I am going to wait until Monday to merge to ensure that if anything fails upstream, someone is around to help fix it.

**Review by beckermr — APPROVED** [review]
Thanks a bunch for this!

Do not merge until Monday!

**Pull request merged**
