### PR TITLE
patch xpublish for pydantic<2

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [X] Ran `python show_diff.py` and posted the output as part of the PR.
* [X] Modifications won't affect packages built in the future. 

Diff:

```
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::xpublish-0.3.0-pyhd8ed1ab_0.conda
-    "zarr"
+    "zarr",
+    "pydantic<2"
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::clad-1.2-clang8_h502a2d1_0.conda
-    "libllvm8 8.0.1 hc9558a2_0",
+    "libllvm8 >=8.0.1,<8.1.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::clad-1.2-clang8_hcb76d2d_0.conda
-    "libllvm8 8.0.1 h770b8ee_0"
+    "libllvm8 >=8.0.1,<8.1.0a0"
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
```

The `libllvm8` change seems to be an artifact from some other change.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Filipe! 🙏

**Comment by jakirkham** [comment]
Maybe I missed it, but did we send a PR to the feedstock to update the dependency constraint?

**Comment by ocefpaf** [comment]
> Maybe I missed it, but did we send a PR to the feedstock to update the dependency constraint?

They issued a new version and I don't think there will be a new build number for that one.

**Comment by jakirkham** [comment]
Ah ok. Was wondering if that might be the case

**Pull request merged**
