### PR TITLE
Use `__cuda` in `nccl` repodata patch

### PR DESCRIPTION
**Pull request by jakirkham**
Potential revised approach of PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/467 )

<hr>

Checklist
* [ ] Ran `python show_diff.py` and posted the output as part of the PR.
* [ ] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by jakirkham** [comment]
Marking as draft until folks have a chance to look

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Review by isuruf — APPROVED** [review]

**Comment by jakirkham** [comment]
Marking as ready

**Comment by jakirkham** [comment]
Thanks you both! 🙏

**Pull request merged**
