### PR TITLE
mudata 0.3.0 requires python>=3.10

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

---

Title says it all

cc: @Shelnutt2, @conda-forge/mudata
xref: https://github.com/scverse/mudata/commit/ce28ac42c941103f1d8521a5d805777d1af3651e, https://github.com/conda-forge/mudata-feedstock/pull/12, https://github.com/conda-forge/mudata-feedstock/pull/13

### CODE REVIEW

**Comment by jdblischak** [comment]
I must be missing something obvious in my patch. Both locally and on Azure, the diff only shows

```
noarch
noarch::apache-airflow-providers-celery-3.8.1-pyhd8ed1ab_0.conda
-    "python =3.8,<4.dev0"
+    "python ==3.8,<4.dev0.*"
```

**Comment by xhochy** [comment]
I don't see something obvious wrong here. Maybe the timestamp is too small?

**Comment by jdblischak** [comment]
> I don't see something obvious wrong here.

@xhochy thanks for the sanity check. I am really confused.

> Maybe the timestamp is too small?

I don't think so. I copied the timestamp from my PR from Tuesday (#831). The binary whose repodata I am trying to patch was uploaded [23 days ago](https://anaconda.org/conda-forge/mudata/files?version=0.3.0):

image

Locally I tried setting a more recent timestamp and also completely removing `timestamp_lt`. Neither made a difference.

**Comment by jdblischak** [comment]
Ugh. I knew it was something tedious. I used the file extension `.yml` instead of `.yaml` 🤦‍♂️ 

Now it's working as intended. I force-pushed the fixed file extension.

```sh
$ python show_diff.py --use-cache --subdirs noarch
================================================================================
================================================================================
noarch
noarch::mudata-0.3.0-pyhd8ed1ab_0.conda
-    "python >=3.9"
+    "python >=3.10"
noarch::apache-airflow-providers-celery-3.8.1-pyhd8ed1ab_0.conda
-    "python =3.8,<4.dev0"
+    "python ==3.8,<4.dev0.*"
```

**Comment by jdblischak** [comment]
[CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1013923&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) is green. The diff shows my mudata patch plus a bunch of other unrelated stuff:

<details>
<summary>
Click here for diff
</summary>

```diff
patching repodata:   0%|          | 0/9 [00:00<?, ?it/s]
patching repodata:  11%|█         | 1/9 [02:43<21:50, 163.82s/it]
================================================================================
================================================================================
noarch
noarch::mudata-0.3.0-pyhd8ed1ab_0.conda
-    "python >=3.9"
+    "python >=3.10"
noarch::apache-airflow-providers-celery-3.8.1-pyhd8ed1ab_0.conda
-    "python =3.8,<4.dev0"
+    "python ==3.8,<4.dev0.*"


patching repodata:  22%|██▏       | 2/9 [02:44<07:55, 67.91s/it] 
================================================================================
================================================================================
linux-armv7l


patching repodata:  33%|███▎      | 3/9 [05:13<10:29, 104.92s/it]
================================================================================
================================================================================
linux-aarch64
linux-aarch64::clang-16.0.6-root_63202_h0ce6a1d_12.conda
linux-aarch64::clang-16.0.6-default_h7e7f49e_12.conda
+  "constrains": [
+    "clang-tools 16.0.6.*",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
+  ],
linux-aarch64::clang-tools-16.0.6-root_63202_h2fb8eeb_12.conda
linux-aarch64::clang-tools-16.0.6-default_he324ac1_12.conda
-    "clangdev 16.0.6"
+    "clang 16.0.6.*",
+    "clangdev 16.0.6",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"


================================================================================
================================================================================
linux-64
linux-64::clang-tools-16.0.6-default_hb5137d0_12.conda
linux-64::clang-tools-16.0.6-root_63202_hae93b4a_12.conda
-    "clangdev 16.0.6"
+    "clang 16.0.6.*",
+    "clangdev 16.0.6",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
linux-64::clang-16.0.6-default_h9e3a008_12.conda
linux-64::clang-16.0.6-root_63202_hd2d6f35_12.conda
+  "constrains": [
+    "clang-tools 16.0.6.*",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
+  ],


patching repodata:  44%|████▍     | 4/9 [07:11<09:09, 109.87s/it]
patching repodata:  56%|█████▌    | 5/9 [07:24<05:00, 75.15s/it] 
================================================================================
================================================================================
linux-ppc64le
linux-ppc64le::clang-16.0.6-root_63202_h22ad045_12.conda
linux-ppc64le::clang-16.0.6-default_hf9b52e6_12.conda
+  "constrains": [
+    "clang-tools 16.0.6.*",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
+  ],
linux-ppc64le::clang-tools-16.0.6-root_63202_h7e73a20_12.conda
linux-ppc64le::clang-tools-16.0.6-default_h9f58072_12.conda
-    "clangdev 16.0.6"
+    "clang 16.0.6.*",
+    "clangdev 16.0.6",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"


patching repodata:  67%|██████▋   | 6/9 [09:27<04:34, 91.35s/it]
================================================================================
================================================================================
osx-arm64
osx-arm64::clang-tools-16.0.6-root_63202_hd460cd1_12.conda
osx-arm64::clang-tools-16.0.6-default_h146c034_12.conda
-    "clangdev 16.0.6"
+    "clang 16.0.6.*",
+    "clangdev 16.0.6",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
osx-arm64::clang-16.0.6-root_63202_h2705a9c_12.conda
osx-arm64::clang-16.0.6-default_h360f5da_12.conda
+  "constrains": [
+    "clang-tools 16.0.6.*",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
+  ],


patching repodata:  78%|███████▊  | 7/9 [09:46<02:15, 67.78s/it]
================================================================================
================================================================================
win-32


patching repodata:  89%|████████▉ | 8/9 [13:22<01:54, 114.91s/it]
================================================================================
================================================================================
osx-64
osx-64::clang-tools-16.0.6-default_hb173f14_12.conda
-    "clangdev 16.0.6"
+    "clang 16.0.6.*",
+    "clangdev 16.0.6",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
osx-64::clang-16.0.6-default_he371ed4_12.conda
+  "constrains": [
+    "clang-tools 16.0.6.*",
+    "llvm 16.0.6.*",
+    "llvm-tools 16.0.6.*",
+    "llvmdev 16.0.6.*"
+  ],


patching repodata: 100%|██████████| 9/9 [14:16<00:00, 95.92s/it] 
```

</details>

**Comment by jdblischak** [comment]
@conda-forge/core @xhochy ready for review

**Comment by jdblischak** [comment]
Diff in [CI run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1017693&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) is clean now. It only includes the patch from this PR:

<details>
<summary>
Click here for diff
</summary>

```
patching repodata:   0%|          | 0/9 [00:00<?, ?it/s]
================================================================================
================================================================================
noarch
noarch::mudata-0.3.0-pyhd8ed1ab_0.conda
-    "python >=3.9"
+    "python >=3.10"


patching repodata:  11%|█         | 1/9 [02:16<18:15, 136.88s/it]
================================================================================
================================================================================
linux-armv7l


patching repodata:  22%|██▏       | 2/9 [02:17<06:37, 56.81s/it] 

patching repodata:  33%|███▎      | 3/9 [04:20<08:40, 86.75s/it]================================================================================
================================================================================
linux-aarch64



patching repodata:  44%|████▍     | 4/9 [05:50<07:22, 88.41s/it]================================================================================
================================================================================
linux-64


patching repodata:  56%|█████▌    | 5/9 [06:07<04:10, 62.60s/it]
================================================================================
================================================================================
linux-ppc64le


patching repodata:  67%|██████▋   | 6/9 [07:52<03:50, 76.94s/it]
================================================================================
================================================================================
osx-arm64


================================================================================
================================================================================
win-32


patching repodata:  78%|███████▊  | 7/9 [08:08<01:53, 56.99s/it]
patching repodata:  89%|████████▉ | 8/9 [10:58<01:32, 92.91s/it]
================================================================================
================================================================================
osx-64


patching repodata: 100%|██████████| 9/9 [11:53<00:00, 81.19s/it]
================================================================================
================================================================================
win-64


patching repodata: 100%|██████████| 9/9 [11:53<00:00, 79.31s/it]
```

</details>

**Comment by jdblischak** [comment]
@conda-forge/core @xhochy ready for review

**Review by xhochy — APPROVED** [review]

**Comment by jdblischak** [comment]
I confirmed the mudata 0.3.0 patch works as intended:

```sh
# In a py39 env, mudata 0.2.4 is installed
mamba create --dry-run -n test -c conda-forge --override-channels python=3.9 mudata
##  + python                  3.9.19  h0755675_0_cpython      conda-forge     Cached
##  + mudata                   0.2.4  pyhd8ed1ab_0            conda-forge       29kB

# In a py310 env, the latest mudata 0.3.1 is installed
mamba create --dry-run -n test -c conda-forge --override-channels python=3.10 mudata
##  + python                 3.10.14  hd12c33a_0_cpython       conda-forge     Cached
##  + mudata                   0.3.1  pyhd8ed1ab_0             conda-forge       41kB

# mudata 0.3.0 (the one patched by this PR) can be installed with py310 but not py39
mamba create --dry-run -n test -c conda-forge --override-channels python=3.10 mudata=0.3.0
##  + python                 3.10.14  hd12c33a_0_cpython       conda-forge     Cached
##  + mudata                   0.3.0  pyhd8ed1ab_1             conda-forge       40kB
mamba create --dry-run -n test -c conda-forge --override-channels python=3.9 mudata=0.3.0
## Could not solve for environment specs
## The following packages are incompatible
## ├─ mudata 0.3.0**  is installable and it requires
## │  └─ python >=3.10  with the potential options
## │     ├─ python [3.10.0|3.10.1|...|3.12.5], which can be installed;
## │     └─ python [3.12.0rc3|3.13.0rc1] would require
## │        └─ _python_rc, which does not exist (perhaps a missing channel);
## └─ python 3.9**  is not installable because it conflicts with any installable versions previously reported.
```

**Pull request merged**
