### PR TITLE
pin urllib3<2 in anaconda-client

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [ ] Ran `python show_diff.py` and posted the output as part of the PR.
* [X] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by jaimergp** [comment]
Addresses https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/242

**Review by beckermr — CHANGES_REQUESTED** [review]
Don't we want to append <2 to all urllib entries regardless of the lower limit?

**Comment by jakirkham** [comment]
Thanks Jaime! 🙏

Should we [update the `urllib3` constraint in `anaconda-client`]( https://github.com/conda-forge/anaconda-client-feedstock/blob/582c0d140e048872184d80d3da042dda888c8b00/recipe/meta.yaml#L41 ) as well?

**Comment by jaimergp** [comment]
> Don't we want to append <2 to all urllib entries regardless of the lower limit?

I think that's the only urllib3 requirement added. Let me check though.

**Comment by jaimergp** [comment]
Yea, it's the only one. Grep for urllib3 in https://api.anaconda.org/package/conda-forge/anaconda-client/files.

**Comment by jaimergp** [comment]
> Should we [update the urllib3 constraint in anaconda-client](https://github.com/conda-forge/anaconda-client-feedstock/blob/582c0d140e048872184d80d3da042dda888c8b00/recipe/meta.yaml#L41) as well?

Technically not needed, and maybe the next version has fixed the import problem, or upstream has updated their pins accordingly and the feedstock should reflect that. I say we wait til next release to adjust if needed, but we do need to remember about it 😬 No strong feelings either way.

**Comment by peterbygrave** [comment]
This is more of a comment to link up relevant work:

I'm always uncertain on who is responsible for the pinning, but opened PR on anaconda-client-feedstock to pin urllib3<2 in a build-1 package: https://github.com/conda-forge/anaconda-client-feedstock/pull/41

This is having consequences in libraries that depend upon it like https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/242

Always keen to learn what the best-practices are in such situations.

**Comment by jakirkham** [comment]
Thanks Peter! 🙏

Usually we...

1. Fix the package requirements in a `build/number` bump
2. Make a repodata patch for prior builds of the package

Jaime did 2 and you did 1. So think we are all set here 🙂

As the conda-forge channel is mirrored to a CDN, there can be some lag between when a package is published and when it is available. This usually isn't too long (less than 1hr, usually much less). Though sometimes there are issues. Please let us know if you are seeing any

**Comment by jakirkham** [comment]
Think we may still be missing some from the repodata patch

Saw the following locally...

<details>

```bash
$ conda update --all
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): -done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-client-1.8.0      |     pyhd8ed1ab_0          71 KB  conda-forge
    brotli-1.0.9               |       h166bdaf_8          18 KB  conda-forge
    brotli-bin-1.0.9           |       h166bdaf_8          20 KB  conda-forge
    libbrotlicommon-1.0.9      |       h166bdaf_8          66 KB  conda-forge
    libbrotlidec-1.0.9         |       h166bdaf_8          33 KB  conda-forge
    libbrotlienc-1.0.9         |       h166bdaf_8         288 KB  conda-forge
    urllib3-2.0.2              |     pyhd8ed1ab_0          95 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         592 KB

The following NEW packages will be INSTALLED:

  brotli             conda-forge/linux-64::brotli-1.0.9-h166bdaf_8 
  brotli-bin         conda-forge/linux-64::brotli-bin-1.0.9-h166bdaf_8 
  libbrotlicommon    conda-forge/linux-64::libbrotlicommon-1.0.9-h166bdaf_8 
  libbrotlidec       conda-forge/linux-64::libbrotlidec-1.0.9-h166bdaf_8 
  libbrotlienc       conda-forge/linux-64::libbrotlienc-1.0.9-h166bdaf_8 

The following packages will be UPDATED:

  urllib3                              1.26.15-pyhd8ed1ab_0 --> 2.0.2-pyhd8ed1ab_0 

The following packages will be DOWNGRADED:

  anaconda-client                       1.11.2-pyhd8ed1ab_1 --> 1.8.0-pyhd8ed1ab_0 


Proceed ([y]/n)? n
```

</details>

**Comment by jaimergp** [comment]
`anaconda-client` 1.8.0 didn't have `urllib3` as a requirement.

image


Back then, it imported things via `requests`:

https://github.com/Anaconda-Platform/anaconda-client/blob/1.8.0/binstar_client/requests_ext.py#L11

So maybe we have to patch `requests`?

**Comment by jaimergp** [comment]
`requests` used to pin `urllib3` (see https://github.com/psf/requests/issues/6432), but the last version (2.31) [lifted](https://github.com/conda-forge/requests-feedstock/pull/63/files) that, hence why we are seeing the error now.

So I think we need to pin `requests` in those old versions that didn't depend on urllib3 directly.

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/457 @jakirkham

**Pull request merged**
