### PR TITLE
Revert pinning libxml2 looser

### PR DESCRIPTION
**Pull request by xhochy**
Diff: https://gist.github.com/xhochy/d034158c956158074e10b2464ec0367c

### CODE REVIEW

**Comment by hmaarrfk** [comment]
if you are sure you don't need to add "pin_stricter" then go for it!

**Comment by xhochy** [comment]
I would leave this around at least until tomorrow morning or until @isuruf also gets a chance to review it.

**Comment by hmaarrfk** [comment]
I think a related question: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3368

@xhochy could you also link us to any feedstocks that show the issue?

**Comment by hmaarrfk** [comment]
```
$ mamba create --name xml libxmlsec1 python --channel conda-forge --override-channels

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.27.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['libxmlsec1', 'python']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Transaction

  Prefix: /home/mark/mambaforge/envs/xml

  Updating specs:

   - libxmlsec1
   - python


  Package               Version  Build               Channel                    Size
──────────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex           0.1  conda_forge         conda-forge/linux-64     Cached
  + _openmp_mutex           4.5  2_gnu               conda-forge/linux-64     Cached
  + bzip2                 1.0.8  h7f98852_4          conda-forge/linux-64     Cached
  + ca-certificates   2022.9.24  ha878542_0          conda-forge/linux-64     Cached
  + gettext            0.19.8.1  h27087fc_1009       conda-forge/linux-64     Cached
  + icu                    70.1  h27087fc_0          conda-forge/linux-64     Cached
  + ld_impl_linux-64     2.36.1  hea4e1c9_2          conda-forge/linux-64     Cached
  + libffi                3.4.2  h7f98852_5          conda-forge/linux-64     Cached
  + libgcc-ng            12.1.0  h8d9b700_16         conda-forge/linux-64     Cached
  + libgcrypt            1.10.1  h166bdaf_0          conda-forge/linux-64     Cached
  + libgomp              12.1.0  h8d9b700_16         conda-forge/linux-64     Cached
  + libgpg-error           1.45  hc0c96e0_0          conda-forge/linux-64     Cached
  + libiconv               1.17  h166bdaf_0          conda-forge/linux-64     Cached
  + libnsl                2.0.0  h7f98852_0          conda-forge/linux-64     Cached
  + libsqlite            3.39.4  h753d276_0          conda-forge/linux-64     Cached
  + libstdcxx-ng         12.1.0  ha89aaad_16         conda-forge/linux-64     Cached
  + libtool               2.4.6  h9c3ff4c_1008       conda-forge/linux-64     Cached
  + libuuid              2.32.1  h7f98852_1000       conda-forge/linux-64     Cached
  + libxml2              2.10.2  h4c7fe37_1          conda-forge/linux-64     Cached
  + libxmlsec1           1.2.34  h5614a37_0          conda-forge/linux-64     Cached
  + libxslt              1.1.35  h8affb1d_0          conda-forge/linux-64     Cached
  + libzlib              1.2.12  h166bdaf_4          conda-forge/linux-64     Cached
  + ncurses                 6.3  h27087fc_1          conda-forge/linux-64     Cached
  + openssl              1.1.1q  h166bdaf_0          conda-forge/linux-64     Cached
  + pip                  22.2.2  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + python               3.10.6  h582c2e5_0_cpython  conda-forge/linux-64       30MB
  + readline              8.1.2  h0f457ee_0          conda-forge/linux-64     Cached
  + setuptools           65.4.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + tk                   8.6.12  h27826a3_0          conda-forge/linux-64     Cached
  + tzdata                2022d  h191b570_0          conda-forge/noarch       Cached
  + wheel                0.37.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + xz                    5.2.6  h166bdaf_0          conda-forge/linux-64     Cached
  + zlib                 1.2.12  h166bdaf_4          conda-forge/linux-64     Cached

  Summary:

  Install: 33 packages

  Total download: 30MB

──────────────────────────────────────────────────────────────────────────────────────

python                                              30.4MB @  42.3MB/s  0.7s
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate xml

To deactivate an active environment, use

     $ mamba deactivate

(base) ✔ ~ [fixup_video_tests_for_1060|✔]
09:58 $ mamba activate xml
(xml) ✔ ~ [fixup_video_tests_for_1060|✔]
09:58 $ python -c "from ctypes import CDLL; CDLL('libxmlsec1.so')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/mambaforge/envs/xml/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mark/mambaforge/envs/xml/lib/python3.10/lib-dynload/../../libxmlsec1.so: undefined symbol: xmlNanoFTPInit, version LIBXML2_2.4.30
```

**Comment by hmaarrfk** [comment]
One reason why is that it might have been deprecated in 2.10 which may have triggered some different compilation options:
https://gitlab.gnome.org/GNOME/libxml2/-/commit/9e0ca5a19f86299efee67598ccd4b797dc219002

**Pull request closed without merging**
