### PR TITLE
add patch (enforce numpy<=1.19) for sigpy_0.1.25_1 build

### PR DESCRIPTION
**Pull request by gschramm**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [ ] Modifications won't affect packages built in the future. 

<!-- Put any other comments or information here --!>

### CODE REVIEW

**Comment by gschramm** [comment]
@zklaus to be checked

**Comment by gschramm** [comment]
my first patch PR. The aim is to correct the `numpy` dependency on 0.1.25_1 (has to be `numpy <= 1.19` because `np.float` was deprecated in 1.20)

**Comment by gschramm** [comment]
output of `python show_diff.py`
```
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
osx-arm64
osx-arm64::clang-17.0.6-hc359061_0.conda
+  "constrains": [
+    "clang-tools 17.0.6.*",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
+  ],
osx-arm64::clang-tools-17.0.6-default_ha3f7cdb_0.conda
-    "clangdev 17.0.6"
+    "clang 17.0.6.*",
+    "clangdev 17.0.6",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
================================================================================
================================================================================
linux-aarch64
linux-aarch64::clang-17.0.6-h5271726_0.conda
+  "constrains": [
+    "clang-tools 17.0.6.*",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
+  ],
linux-aarch64::clang-tools-17.0.6-default_h95d19f2_0.conda
-    "clangdev 17.0.6"
+    "clang 17.0.6.*",
+    "clangdev 17.0.6",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
================================================================================
================================================================================
linux-ppc64le
linux-ppc64le::clang-17.0.6-h381f82a_0.conda
+  "constrains": [
+    "clang-tools 17.0.6.*",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
+  ],
linux-ppc64le::clang-tools-17.0.6-default_ha79e3c0_0.conda
-    "clangdev 17.0.6"
+    "clang 17.0.6.*",
+    "clangdev 17.0.6",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
================================================================================
================================================================================
noarch
noarch::sigpy-0.1.25-pyha21a80b_1.conda
-    "numpy",
+    "numpy <=1.19",
================================================================================
================================================================================
win-64
================================================================================
================================================================================
osx-64
osx-64::clang-17.0.6-h897cf5c_0.conda
+  "constrains": [
+    "clang-tools 17.0.6.*",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
+  ],
osx-64::clang-tools-17.0.6-default_h7e3957e_0.conda
-    "clangdev 17.0.6"
+    "clang 17.0.6.*",
+    "clangdev 17.0.6",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
================================================================================
================================================================================
linux-64
linux-64::clang-17.0.6-ha0738ec_0.conda
+  "constrains": [
+    "clang-tools 17.0.6.*",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
+  ],
linux-64::clang-tools-17.0.6-default_h1cdf331_0.conda
-    "clangdev 17.0.6"
+    "clang 17.0.6.*",
+    "clangdev 17.0.6",
+    "llvm 17.0.6.*",
+    "llvm-tools 17.0.6.*",
+    "llvmdev 17.0.6.*"
```

**Comment by beckermr** [comment]
The llvm patches are normal to see. Lgtm.

**Comment by gschramm** [comment]
Can someone explain what "Modifications won't affect packages built in the future" means?

**Comment by beckermr** [comment]
It means that this patch won't match to new packages that get built. Your patch is fine since it matches to a specific artifact.

**Comment by zklaus** [comment]
Somehow we left this PR in limbo. Should we still merge, @beckermr?

**Pull request merged**
