### PR TITLE
Add new dependency for openslide 4.0.0 on libdicom

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: https://github.com/conda-forge/openslide-feedstock/pull/25

cc: @kaczmarj

Checklist

* [ ] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [ ] Ran `python show_diff.py` and posted the output as part of the PR.
* [ ] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by jakirkham** [comment]
Was this dependency also added to the package somewhere?

**Comment by jakirkham** [comment]
Also thanks for looking into this Mark! 🙏

**Comment by hmaarrfk** [comment]
Yes, new dependency in version 4.0.0, but we didn't have a run_export in the package. nor a test in the binary to catch it.

**Comment by jakirkham** [comment]
Ah ok. That context helps. Thanks Mark 🙏

So the steps were:

* Add a `run_export` to `libdicom` ( https://github.com/conda-forge/libdicom-feedstock/pull/5 )
* Patch the existing `openslide` packages

Should we add `libdicom` as a `run` dependency in `openslide` as well (just in case an older `libdicom` package without the `run_export` is used for the build)?

**Comment by hmaarrfk** [comment]
> Should we add libdicom as a run dependency in openslide as well (just in case an older libdicom package without the run_export is used for the build)?

no a test is being added instead.

**Comment by jakirkham** [comment]
Ok thanks! Updated the summary above. Does that look better

**Comment by hmaarrfk** [comment]
yes.

**Pull request merged**
