### PR TITLE
don't remove track_features for pypy

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Is this related to the [build failure on `main`]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=479001&view=logs&jobId=516f237f-98f1-50a4-0946-c43fe5437b81&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=68e286c4-c87b-5a2e-10c4-f21f8bc51a62 )?

**Comment by isuruf** [comment]
Yes

**Comment by isuruf** [comment]
This is ready now

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Isuru! 😄

Feel free to merge when you are ready 🙂

**Comment by leofang** [comment]
Thanks!

**Pull request merged**
