### PR TITLE
Don't patch llvm packages for new versions

### PR DESCRIPTION
**Pull request by isuruf**
Checklist

* [ ] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [ ] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [ ] Ran `python show_diff.py` and posted the output as part of the PR.
* [ ] Modifications won't affect packages built in the future. 

cc @beckermr @h-vetinari

### CODE REVIEW

**Comment by beckermr** [comment]
The PR is clear and thank you! Can we xref any known issues about this or why we stopped patching now?

**Comment by isuruf** [comment]
I don't remember why I patched it in the first place. Let's try not patching for new versions.

**Comment by beckermr** [comment]
precommit.ci autofix

**Comment by h-vetinari** [comment]
Thanks.

> Can we xref any known issues about this or why we stopped patching now?

https://github.com/conda-forge/llvmdev-feedstock/pull/142, https://github.com/conda-forge/llvmdev-feedstock/issues/141 are the ones I'm aware of. Looking at the git history, this seems to come from #20, which doesn't have other references AFAICT.

**Pull request merged**
