### PR TITLE
Pin cuTENSOR 1.2.2.5 exactly

### PR DESCRIPTION
**Pull request by leofang**
To prepare for https://github.com/conda-forge/cutensor-feedstock/issues/11. Currently we only release one version (1.2.2.5) on Conda-Forge, so this should be sufficient.

cc: @jakirkham @mnicely

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
Hmmm...Running `show_diff.py` locally shows CuPy v8.x packages are correctly patched, but nothing is done to CuPy v9.0. Looking into it...

**Comment by leofang** [comment]
> Hmmm...Running `show_diff.py` locally shows CuPy v8.x packages are correctly patched, but nothing is done to CuPy v9.0. Looking into it...

Need to patch the `constrains` section too. Fixed in 531b575.

**Review by kkraus14 — APPROVED** [review]

**Comment by leofang** [comment]
Thanks, @kkraus14!

**Comment by leofang** [comment]
@jakirkham @conda-forge/core Do you know if there is a way to run this patch again? I am seeing new packages (CuPy 9.2.0) not patched correctly, likely because they were uploaded just recently, and now with conda-forge/cutensor-feedstock#13 it causes a problem, because the uploaded CuPy packages cannot work with the newer cuTENSOR package (1.3).

**Comment by leofang** [comment]
> @jakirkham @conda-forge/core Do you know if there is a way to run this patch again? I am seeing new packages (CuPy 9.2.0) not patched correctly, likely because they were uploaded just recently, and now with [conda-forge/cutensor-feedstock#13](https://github.com/conda-forge/cutensor-feedstock/pull/13) it causes a problem, because the uploaded CuPy packages cannot work with the newer cuTENSOR package (1.3).

See #147.

**Pull request merged**
