### PR TITLE
update pins for anaconda-cloud-cli 0.1.0

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

show_diff.py output limited to this pacakge

```
noarch::anaconda-cloud-cli-0.2.0-pyhd8ed1ab_0.conda
-    "anaconda-cli-base >=0.2",
-    "anaconda-client >=1.12.2",
-    "anaconda-cloud-auth >=0.3",
+    "anaconda-cli-base >=0.2,<0.3",
+    "anaconda-client >=1.12.2,<1.13",
+    "anaconda-cloud-auth >=0.3,<0.6",
noarch::anaconda-cloud-cli-0.1.0-pyhd8ed1ab_0.conda
-    "anaconda-cli-base",
-    "anaconda-cloud-auth",
+    "anaconda-cli-base <0.3.0",
+    "anaconda-cloud-auth <0.6.0",
```

### CODE REVIEW

**Review by mattkram — APPROVED** [review]
These all look correct to me.

**Comment by AlbertDeFusco** [comment]
Oh. Done.

**Comment by AlbertDeFusco** [comment]
Hi @xhochy, is there something else that needs to be done here?

**Comment by jdblischak** [comment]
FYI the feedstock CI failed on the merge commit https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/commit/12ed7ea046ec2ddf8425bcf9a75e7471644d2a23

**Comment by AlbertDeFusco** [comment]
oh, I didn't notice the merge failure. Thanks @jdblischak. Do you have a recommendation? I'll take a look at what's going on today.

**Comment by jdblischak** [comment]
> Do you have a recommendation? I'll take a look at what's going on today.

@AlbertDeFusco you don't have to do anything. While the CI did fail on the merge commit from this PR, the CI was subsequently fixed and succeeded. Thus your patch is already in effect, and there is no further action you need to take.

Demo:

```
$ mamba create --dry-run -n test -c conda-forge anaconda-cloud-cli=0.1 anaconda-cli-base=0.3

Looking for: ['anaconda-cloud-cli=0.1', 'anaconda-cli-base=0.3']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following packages are incompatible
├─ anaconda-cli-base 0.3**  is requested and can be installed;
└─ anaconda-cloud-cli 0.1**  is not installable because it requires
   └─ anaconda-cli-base <0.3.0 , which conflicts with any installable versions previously reported.
```

**Pull request merged**
