### PR TITLE
MNT: rerender

### LINKED ISSUE #363: @conda-forge-admin rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #363.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #363

### CODE REVIEW

**Comment by jakirkham** [comment]
This seems to be a no-op. Is there some additional context on why this is needed somewhere?

**Comment by beckermr** [comment]
I marked a bunch of packages I maintain for myself broken in the UI since I was in a rush. Needs a rebuild here to propagate.

**Comment by jakirkham** [comment]
Are we able to just restart CI here? Happy to do that if you'd like

**Comment by beckermr** [comment]
The PR does the same thing as a CI restart but bumps folks less. I'll do that in the azure interface next time.

**Comment by jakirkham** [comment]
Added a [build here]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=622123&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97 )

**Comment by jakirkham** [comment]
Hopefully that helps get out even faster 🐎

Thanks Matt! 🙏

**Comment by beckermr** [comment]
Thank you!

**Comment by jakirkham** [comment]
Ofc. FWIW the build just finished.

**Pull request closed without merging**
