### PR TITLE
Fix duet-python deps

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This was missed originally.` typing-extensions ==3.10.0` is correct but it's currently only `typing-extensions`.
Feedstock: https://github.com/conda-forge/duet-python-feedstock
Upstream: https://github.com/google/duet/blob/v0.2.5/requirements.txt

### CODE REVIEW

**Comment by BastianZim** [comment]
The only question I have is if this actually the correct way to fix this because the script gives the following output. Should this not show the difference?

```zsh
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::grpcio-status-1.48.0-pyhd8ed1ab_0.tar.bz2
-    "grpcio >=1.46.3",
+    "grpcio >=1.48.0",
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
```

**Comment by BastianZim** [comment]
@conda-forge/core Gentle bump

**Comment by hmaarrfk** [comment]
does this actually cause an error? honestly, i don't see these as being so critical.

Also, while not a rule, I would prefer that you address the issues in the feedstock first (i.e. add the pin) then after that is merged, ask for the "backport" refering the pull request.

The repo-data patch should also be quite specific about the latest first to patch.

Ideally, the error would be documented in the PR or an issue a user raised.

**Comment by BastianZim** [comment]
It just makes `pip check` fail but yes, it’s not super critical, just annoying. 

That's the reason I didn't make a PR yet. This way, all affected versions are explicitly stated and the next one will have the fix in the feedstock. I thought this would be cleaner. 

Yes, that's documented here: https://github.com/conda-forge/duet-python-feedstock/issues/7 and the error is in the PR linked above: https://github.com/conda-forge/fqe-feedstock/pull/6

**Comment by hmaarrfk** [comment]
I think the patches are meant to be idempotent. in either case, it offloads the review process to the feedstock (though I understand the feedstock is just you).

**Comment by BastianZim** [comment]
Ahh ok wasn't sure about that. I know some specify time but I thought this is cleaner. Then I'm fine either way, whichever you prefer. But yes, I'm the only maintainer of all involved feedstocks.

**Comment by hmaarrfk** [comment]
I think that is why a timestamp has been requested. but there is no documentation (that I can find) on how to generate the timestamp. so I take build numbers as good enough for the latest version.

**Comment by hmaarrfk** [comment]
please ping again when you have things addressed in the feedstock if you think this is still relevant.

**Comment by BastianZim** [comment]
I’ll just close it then as it‘s not that important.

**Comment by hmaarrfk** [comment]
sometimes it can help the solvers, but generally these repo-data patches seem to cause alot of churn. I'm not really sure of a better way.

**Pull request closed without merging**
