### PR TITLE
Fix old conda compat

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @mariusvniekerk, @ocefpaf, @tomtal

### CODE REVIEW

**Comment by isuruf** [comment]
Here's the diff for `noarch`.
```
noarch::awkward0-0.15.4-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::awkward0-0.15.5-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::boltons-21.0.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4"
+    "python ==2.7.*|>=3.4"
noarch::cpplint-1.5.5-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6"
+    "python ==2.7.*|>=3.6"
noarch::dbf-0.99.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::dropbox-11.10.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.11.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.12.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.13.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.13.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.13.2-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.13.3-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.14.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.15.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.2.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.4.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.4.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.6.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.7.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.8.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::dropbox-11.9.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::flake8-docstrings-1.6.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::gridded-0.3.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.7",
+    "python ==2.7.*|>=3.7",
noarch::incqueryserver-api-python-client-0.17.1-pyhd8ed1ab_1.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::incqueryserver-api-python-client-0.18.0.post1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::incqueryserver-api-python-client-0.19.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::incqueryserver-api-python-client-0.19.0.dev2-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::incqueryserver-api-python-client-0.19.0.dev2-pyhd8ed1ab_1.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::incqueryserver-api-python-client-0.20.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::lazy_import-0.2.2-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::lbnightlytools-3.0.26-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.27-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.28-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.29-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.30-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.31-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.32-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.33-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.34-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.35-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::lbnightlytools-3.0.36-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::nimfa-1.4.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::orator-0.9.9-py_0.tar.bz2
-    "python =2.7|>=3.5,<3.7",
+    "python ==2.7.*|>=3.5,<3.7",
noarch::pathos-0.2.8-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6"
+    "python ==2.7.*|>=3.6"
noarch::pmgr-2.0.2-pyhd8ed1ab_0.tar.bz2
-    "mysqlclient =1.3.12|>=2.0.3",
+    "mysqlclient ==1.3.12.*|>=2.0.3",
noarch::pmgr-2.0.2-pyhd8ed1ab_1.tar.bz2
-    "mysqlclient =1.3.12|>=2.0.3",
+    "mysqlclient ==1.3.12.*|>=2.0.3",
noarch::pox-0.3.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6"
+    "python ==2.7.*|>=3.6"
noarch::ppft-1.6.6.4-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::pycodestyle-2.7.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::pyflakes-2.3.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::pyflakes-2.3.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::pytest-clarity-1.0.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::python-docx-0.8.11-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4"
+    "python ==2.7.*|>=3.4"
noarch::python-irodsclient-0.8.6-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::python-irodsclient-0.9.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::python-irodsclient-1.0.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::sage-flatsurf-0.1-py_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::sage-flatsurf-0.3-py_0.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::sphinx-argparse-0.2.5-pyhd8ed1ab_1.tar.bz2
-    "python =2.7|>=3.6",
+    "python ==2.7.*|>=3.6",
noarch::sqlalchemy-redshift-0.8.3-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::sqlalchemy-redshift-0.8.4-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.4",
+    "python ==2.7.*|>=3.4",
noarch::tabulate-0.8.8-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::tabulate-0.8.9-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::texttable-1.6.4-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::uproot-methods-0.8.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::uproot-methods-0.9.2-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::uproot3-3.14.3-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::uproot3-3.14.4-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::uproot3-methods-0.10.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::uproot3-methods-0.10.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5"
+    "python ==2.7.*|>=3.5"
noarch::verta-0.17.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.17.2-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.17.3-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.17.4-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.17.5-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.17.6-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.18.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.18.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.18.2-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.19.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::verta-0.19.1-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.5",
+    "python ==2.7.*|>=3.5",
noarch::wheel-0.37.0-pyhd8ed1ab_0.tar.bz2
-    "python =2.7|>=3.6"
+    "python ==2.7.*|>=3.6"
```

**Comment by tomtal** [comment]
Thank you for making this fix, @isuruf!  The ran into this on Conda 4.3.21. Any way to verify this fixes the issue and also does not break temporary hack we put in (and rolling out in our services) before this change becomes available on conda-forge?

**Comment by isuruf** [comment]
> Any way to verify this fixes the issue and also does not break temporary hack we put in (and rolling out in our services) before this change becomes available on conda-forge?

Not easily. You'd have to build is feedstock, apply the repodata patch and build a new index locally, and point conda to this index locally.

**Comment by isuruf** [comment]
@conda-forge/core, this is ready for review.

**Review by xhochy — APPROVED** [review]

**Comment by CJ-Wright** [comment]
@core Should we have a timeframe for dropping old conda support so we can use some of the newer operators?

**Pull request merged**
