### PR TITLE
ENH set upper bound for mpl for proplot

### LINKED ISSUE #201: patch proplot so it has an upper bound at mpl 3.4
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

closes #201

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
diff:

```
$ python recipe/show_diff.py 
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::proplot-0.3.1-py_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.3.1-py_1.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.4.0-py_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.4.0-py_1.tar.bz2
-    "matplotlib",
+    "matplotlib <3.5.0a0",
noarch::proplot-0.4.1-py_0.tar.bz2
-    "matplotlib",
+    "matplotlib <3.5.0a0",
noarch::proplot-0.4.2-py_0.tar.bz2
-    "matplotlib",
+    "matplotlib <3.5.0a0",
noarch::proplot-0.4.3-py_0.tar.bz2
-    "matplotlib",
+    "matplotlib <3.5.0a0",
noarch::proplot-0.5.0-py_0.tar.bz2
-    "matplotlib",
+    "matplotlib <3.5.0a0",
noarch::proplot-0.5.0-py_1.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.6.1-py_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.6.3-py_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.6.4-py_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.7.0-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.8.0-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.8.1-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.9.0-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.9.1-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.9.2-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.9.3-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.9.4-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
noarch::proplot-0.9.5-pyhd8ed1ab_0.tar.bz2
-    "matplotlib-base",
+    "matplotlib-base <3.5.0a0",
```

**Comment by beckermr** [comment]
cc @conda-forge/proplot

**Comment by lukelbd** [comment]
Thanks!

**Pull request merged**
