### PR TITLE
Limit python and xarray version for imod<=0.18.1

### PR DESCRIPTION
**Pull request by JoerivanEngelen**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

Results show diff:

```
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
linux-ppc64le
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
linux-aarch64
================================================================================
================================================================================
noarch
noarch::imod-0.11.2-pyhd8ed1ab_0.tar.bz2
noarch::imod-0.11.3-pyhd8ed1ab_0.tar.bz2
noarch::imod-0.11.4-pyhd8ed1ab_0.tar.bz2
noarch::imod-0.11.5-pyhd8ed1ab_0.conda
noarch::imod-0.11.6-pyhd8ed1ab_0.conda
noarch::imod-0.12.0-pyhd8ed1ab_0.conda
noarch::imod-0.13.0-pyhd8ed1ab_0.conda
noarch::imod-0.13.1-pyhd8ed1ab_0.conda
noarch::imod-0.13.2-pyhd8ed1ab_0.conda
noarch::imod-0.14.0-pyhd8ed1ab_0.conda
noarch::imod-0.14.1-pyhd8ed1ab_0.conda
-    "xarray >=0.15",
+    "xarray >=0.15,<2024.10.0a0",
noarch::imod-0.10.0-py_0.tar.bz2
noarch::imod-0.10.1-py_0.tar.bz2
-    "xarray >=0.15"
+    "xarray >=0.15,<2024.10.0a0"
noarch::imod-0.6.1-py_0.tar.bz2
noarch::imod-0.7.0-py_0.tar.bz2
noarch::imod-0.7.1-py_0.tar.bz2
noarch::imod-0.8.0-py_0.tar.bz2
noarch::imod-0.9.0-py_0.tar.bz2
noarch::imod-0.9.0-py_1.tar.bz2
-    "xarray >=0.11"
+    "xarray >=0.11,<2024.10.0a0"
noarch::imod-0.15.0-pyhd8ed1ab_0.conda
noarch::imod-0.15.1-pyhd8ed1ab_0.conda
-    "python >=3.10",
+    "python >=3.10,<3.13.0a0",
-    "xarray >=0.15",
+    "xarray >=0.15,<2024.10.0a0",
noarch::imod-0.15.2-pyhd8ed1ab_0.conda
noarch::imod-0.15.3-pyhd8ed1ab_0.conda
noarch::imod-0.16.0-pyhd8ed1ab_0.conda
noarch::imod-0.17.0-pyhd8ed1ab_0.conda
noarch::imod-0.17.1-pyhd8ed1ab_0.conda
noarch::imod-0.17.2-pyhd8ed1ab_0.conda
noarch::imod-0.18.0-pyhd8ed1ab_0.conda
noarch::imod-0.18.1-pyhd8ed1ab_0.conda
-    "python >=3.10",
+    "python >=3.10,<3.13.0a0",
-    "xarray >=2023.08.0",
+    "xarray >=2023.08.0,<2024.10.0a0",
================================================================================
================================================================================
win-64
================================================================================
================================================================================
osx-64
================================================================================
================================================================================
linux-64
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
You need to fix that in the feedstock first, or the next build will also require a patch. See https://github.com/conda-forge/imod-feedstock/blob/main/recipe/meta.yaml#L57

**Comment by JoerivanEngelen** [comment]
Thanks for the fast response, I didn't read the docs carefully enough so I missed that I had to update the feedstock recipe for future releases, but that makes complete sense. I've created a new build on the feedstock which is now merged. https://github.com/conda-forge/imod-feedstock/pull/44 .

Is that sufficient to merge this PR and get the older versions patched as well?

**Comment by ocefpaf** [comment]
> Is that sufficient to merge this PR and get the older versions patched as well?

That is up to you. For "correctness" one could patch everything that is affected. However, we usually patch only the most used one/latest to avoid over patching.

**Comment by JoerivanEngelen** [comment]
Ah yes, good to see you are pragmatic about patching. Thanks for the quick response again and the merge!

**Pull request merged**
