### PR TITLE
Patch pandas dependency for fastparquet=0.7.0

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

xref https://github.com/dask/dask/pull/7907, https://github.com/conda-forge/fastparquet-feedstock/pull/47

cc @martindurant

EDIT: Note I used https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/142 as a template for the changes made here

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks James! 😄

Can you please [run `show_diff.py` from the `recipe` directory]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/readme.md ) and share the results?

**Comment by jrbourbeau** [comment]
Below is the full `show_diff.py` output. The `fastparquet` diff looks right, but I'm not sure where

```
linux-64::libkml-1.3.0-h238a007_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
```

and 

```
win-64::tiledb-py-0.9.2-py36_vc14hdd3148d_0.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.2-py37_vc14h756c2e0_0.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.2-py38_vc14h528aa4e_0.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.2-py39_vc14he219d82_0.tar.bz2
-  "features": "vc14",
```

are coming from 

<details>
<summary>Full output:</summary>

```
(conda-forge-repodata-patches) ➜  conda-forge-repodata-patches-feedstock git:(fastparquet-0.7.0) python recipe/show_diff.py
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::fastparquet-0.7.0-py36h4d9540e_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-64::fastparquet-0.7.0-py37h6f94858_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-64::fastparquet-0.7.0-py38hb5d20a5_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-64::fastparquet-0.7.0-py39hce5d2b2_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-64::libkml-1.3.0-h238a007_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
linux-aarch64::fastparquet-0.7.0-py36hbe810f4_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-aarch64::fastparquet-0.7.0-py37h32d76ca_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-aarch64::fastparquet-0.7.0-py38h5c1ee58_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-aarch64::fastparquet-0.7.0-py39h5cfbcb9_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-aarch64::libkml-1.3.0-h019b1a7_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
linux-ppc64le::fastparquet-0.7.0-py36ha96d7dc_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-ppc64le::fastparquet-0.7.0-py37he662d02_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-ppc64le::fastparquet-0.7.0-py38h9d9f2af_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-ppc64le::fastparquet-0.7.0-py39h3084282_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
linux-ppc64le::libkml-1.3.0-hc41e6c6_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::fastparquet-0.7.0-py36hab44bd3_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
osx-64::fastparquet-0.7.0-py37h238668a_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
osx-64::fastparquet-0.7.0-py38h0793694_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
osx-64::fastparquet-0.7.0-py39hc89836e_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
osx-64::libkml-1.3.0-h8fd9edb_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
osx-arm64::fastparquet-0.7.0-py38h691f20f_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
osx-arm64::fastparquet-0.7.0-py39h20ef057_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
osx-arm64::libkml-1.3.0-h893ab4d_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
win-64::fastparquet-0.7.0-py36h68f0c41_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
win-64::fastparquet-0.7.0-py37hebb4d16_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
win-64::fastparquet-0.7.0-py38hcb5f9af_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
win-64::fastparquet-0.7.0-py39h5d4886f_0.tar.bz2
-    "pandas >=0.19",
+    "pandas >=1.0.0",
win-64::libkml-1.3.0-h9859afa_1014.tar.bz2
-    "expat >=2.3.0,<2.4.0a0",
+    "expat >=2.3.0,<3.0.0a0",
win-64::tiledb-py-0.9.2-py36_vc14hdd3148d_0.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.2-py37_vc14h756c2e0_0.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.2-py38_vc14h528aa4e_0.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.2-py39_vc14he219d82_0.tar.bz2
-  "features": "vc14",
```

</details>

**Comment by jakirkham** [comment]
@conda-forge/core , do we know why these other patches are showing up? From the change in this PR, it's not clear how this would have caused those. So assuming they are showing up for another reason.

**Comment by beckermr** [comment]
This has been happening. Idk specifically about those diffs but we've been merging anyways.

**Comment by jakirkham** [comment]
Interesting thanks for the context Matt 🙂

It does make me worry a little bit that maybe some older patches might not be getting applied (cc @chenghlee in case you have insights here :)

**Comment by jakirkham** [comment]
Going to go ahead and merge, but it would be good to investigate this issue more later

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
