### PR TITLE
Fix pari dependencies

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core this is ready for review.

**Comment by xhochy** [comment]
Can you post the diff?

**Comment by isuruf** [comment]
```
linux-64::cypari2-2.1.2-py36hd30bac0_1.tar.bz2
-    "python_abi 3.6.* *_cp36m"
+    "python_abi 3.6.* *_cp36m",
+    "pari * *_single"
linux-64::cypari2-2.1.2-py37h36024e3_1.tar.bz2
-    "python_abi 3.7.* *_cp37m"
+    "python_abi 3.7.* *_cp37m",
+    "pari * *_single"
linux-64::cypari2-2.1.2-py38h17ed83f_1.tar.bz2
-    "python_abi 3.8.* *_cp38"
+    "python_abi 3.8.* *_cp38",
+    "pari * *_single"
linux-64::cypari2-2.1.2-py39h080b040_1.tar.bz2
-    "python_abi 3.9.* *_cp39"
+    "python_abi 3.9.* *_cp39",
+    "pari * *_single"
linux-64::cysignals-1.10.3-py36he0d4dc2_1.tar.bz2
-    "python_abi 3.6.* *_cp36m"
+    "python_abi 3.6.* *_cp36m",
+    "pari * *_single"
linux-64::cysignals-1.10.3-py37hbfa85f7_1.tar.bz2
-    "python_abi 3.7.* *_cp37m"
+    "python_abi 3.7.* *_cp37m",
+    "pari * *_single"
linux-64::cysignals-1.10.3-py38h8a278f0_1.tar.bz2
-    "python_abi 3.8.* *_cp38"
+    "python_abi 3.8.* *_cp38",
+    "pari * *_single"
linux-64::cysignals-1.10.3-py39ha085c7a_1.tar.bz2
-    "python_abi 3.9.* *_cp39"
+    "python_abi 3.9.* *_cp39",
+    "pari * *_single"
linux-64::eclib-20210503-h363636d_1.tar.bz2
-    "pari >=2.13.2,<3.0a0"
+    "pari >=2.13.2,<3.0a0",
+    "pari * *_single"
linux-64::gap-4.11.0-hce68fbb_8.tar.bz2
-    "zeromq >=4.3.4,<4.4.0a0"
+    "zeromq >=4.3.4,<4.4.0a0",
+    "pari * *_single"
linux-64::giac-1.6.0.47-h1d0a5e6_1.tar.bz2
-    "zlib >=1.2.11,<1.3.0a0"
+    "zlib >=1.2.11,<1.3.0a0",
+    "pari * *_single"
linux-64::lcalc-1.23-hdae8c4a_1005.tar.bz2
-    "pari >=2.13.2,<2.14.0a0"
+    "pari >=2.13.2,<2.14.0a0",
+    "pari * *_single"
```

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
