### PR TITLE
Pin cuTENSOR 1.2.2.5 exactly, again

### PR DESCRIPTION
**Pull request by leofang**
This PR adds an empty commit to re-trigger the patch #141. The reason for re-triggering is that I recently uploaded a bunch of packages under the mistaken assumption that once a repodata patch is issued, it'd be applied to all current and future repodata, but obviously only the current repodata as seen at the time of merge is patched. 

Specifically, this re-triggering will correctly patch CuPy v9.2.0 (conda-forge/cupy-feedstock#134, just merged yesterday) to use cuTENSOR 1.2.2, which is binary incompatible with cuTENSOR 1.3.1 that I just uploaded (conda-forge/cutensor-feedstock#13).

cc: @jakirkham @conda-forge/core

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
```
$ python show_diff.py
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::cupy-9.2.0-py36h0fc7315_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py36h1930939_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py36h25573b8_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py36h4790a05_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py36h7454194_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37h11477cf_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37h3c5eebb_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37h464e165_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37h4fdb0f7_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37h56ca915_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37hc0aaff5_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37hc16ada3_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37hc6e7f7d_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37hfc113e4_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py37hfed0110_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py38h14045e6_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py38h5546af9_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py38h9c1f86d_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py38ha69542f_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py38hc350bd8_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py39h53c10af_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py39h55859a9_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py39h81a3557_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py39h835a156_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::cupy-9.2.0-py39hb309dcf_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-64::graph-tool-2.40-py36hf3098de_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
linux-64::graph-tool-2.40-py37h6056006_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
linux-64::graph-tool-2.40-py38h9a62468_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
linux-64::graph-tool-2.40-py39hc2c1061_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
linux-ppc64le::cupy-9.2.0-py36h883fed4_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-ppc64le::cupy-9.2.0-py37hb59e34e_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-ppc64le::cupy-9.2.0-py37hdf97375_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-ppc64le::cupy-9.2.0-py38h1bc5b83_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
linux-ppc64le::cupy-9.2.0-py39h9b85191_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::graph-tool-2.40-py37h85a0b66_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
osx-64::graph-tool-2.40-py38hdc09010_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
osx-64::graph-tool-2.40-py39h01f136a_0.tar.bz2
-    "expat >=2.2.10,<2.3.0a0",
+    "expat >=2.2.10,<3.0.0a0",
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
win-64::cupy-9.2.0-py36h4641266_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0"
+    "cutensor =1.2.2.5"
win-64::cupy-9.2.0-py36hc806ef2_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0"
+    "cutensor =1.2.2.5"
win-64::cupy-9.2.0-py36he6cd523_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0"
+    "cutensor =1.2.2.5"
win-64::cupy-9.2.0-py36hfdd5185_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py37h72a7169_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py37h9ef161e_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0"
+    "cutensor =1.2.2.5"
win-64::cupy-9.2.0-py37hee0cbde_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0"
+    "cutensor =1.2.2.5"
win-64::cupy-9.2.0-py37hfe954b4_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py38h5fb355a_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py38h66fa806_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py38h8737d37_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py38hf95616d_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0"
+    "cutensor =1.2.2.5"
win-64::cupy-9.2.0-py39h58dc777_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py39h5d933e2_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py39hb2679a4_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::cupy-9.2.0-py39hc474d4a_0.tar.bz2
-    "cutensor >=1.2.2.5,<2.0a0",
+    "cutensor =1.2.2.5",
win-64::tiledb-py-0.9.0-py36_vc14hdd3148d_2.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.0-py37_vc14h756c2e0_2.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.0-py38_vc14h528aa4e_2.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.0-py39_vc14he219d82_2.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.1-py36_vc14hdd3148d_3.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.1-py37_vc14h756c2e0_3.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.1-py38_vc14h528aa4e_3.tar.bz2
-  "features": "vc14",
win-64::tiledb-py-0.9.1-py39_vc14he219d82_3.tar.bz2
-  "features": "vc14",
```

**Comment by isuruf** [comment]
Please send a PR to fix cutensor's `run_exports` first to `cutensor-feedstock`.

**Comment by leofang** [comment]
Hi @isuruf IIUC I think with cuTENSOR 1.3+ the `run_exports` there should be correct. The binary incompatibility from 1.2 to 1.3 is likely a one-off event.

**Comment by isuruf** [comment]
I mean for cutensor 1.2

**Comment by isuruf** [comment]
We are not sure it's going to be a one-off event. So it's better to pin to `x.x`.

**Comment by leofang** [comment]
> We are not sure it's going to be a one-off event. So it's better to pin to `x.x`.

Is this something that we can fix via patching the repodata without publishing another `cutensor` package? The content is correct, only the repodata needs to be fixed, so I assume managing it in this repo is preferred? Thanks.

**Comment by isuruf** [comment]
Nope. `run_exports` can't be patched.

**Comment by leofang** [comment]
Hmmm...OK. So does it mean once a new package is uploaded, we also have to mark the old ones broken?

**Comment by leofang** [comment]
Sorry, this PR no longer makes sense now that #148 is just merged. Let me open an issue in cutensor-feedstock to track the `run_exports` fix and close this one. I can work on it once I return to work.

**Pull request closed without merging**
