### PR TITLE
relax openff-toolkit pin for gufe

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by mikemhenry** [comment]
See https://github.com/OpenFreeEnergy/gufe/issues/280 for more info

**Comment by mikemhenry** [comment]
```
$ python show_diff.py
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
linux-ppc64le
================================================================================
================================================================================
linux-aarch64
================================================================================
================================================================================
noarch
noarch::gufe-0.9.2-pyhd8ed1ab_0.conda
noarch::gufe-0.9.4-pyhd8ed1ab_0.conda
noarch::gufe-0.9.3-pyhd8ed1ab_0.conda
noarch::gufe-0.9.1-pyhd8ed1ab_0.conda
noarch::gufe-0.9.5-pyhd8ed1ab_0.conda
noarch::gufe-0.9.5-pyhd8ed1ab_2.conda
noarch::gufe-0.9.5-pyhd8ed1ab_1.conda
-    "openff-toolkit >=0.13,<0.14",
+    "openff-toolkit >=0.13,<0.15",
================================================================================
================================================================================
win-64
================================================================================
================================================================================
osx-64
================================================================================
================================================================================
linux-64
```

**Review by richardjgowers — APPROVED** [review]
this looks like what we want to achieve, not sure if the error is real or random

**Comment by mikemhenry** [comment]
Ready for review!

@richardjgowers what error? The most recent commit is :green_circle:

**Comment by richardjgowers** [comment]
boh, I thought I'd saw something like a http 523 this morning, looks good now

**Review by xhochy — APPROVED** [review]

**Pull request merged**
