### PR TITLE
Patch virtualenv 20.16.3 build 0

### PR DESCRIPTION
**Pull request by xylar**
Dependencies were not updated

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Output of `show_diff.py`:

```
$ ./show_diff.py 
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::virtualenv-20.16.3-py310hff52083_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.10.* *_cp310",
-    "six >=1.9.0,<2"
+    "python_abi 3.10.* *_cp310"
linux-64::virtualenv-20.16.3-py37h89c1867_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "importlib-metadata >=0.12",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "importlib-metadata >=4.8.3",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.7.* *_cp37m",
-    "six >=1.9.0,<2"
+    "python_abi 3.7.* *_cp37m"
linux-64::virtualenv-20.16.3-py38h373033e_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8 *_pypy38_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.8 *_pypy38_pp73"
linux-64::virtualenv-20.16.3-py38h578d9bd_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8.* *_cp38",
-    "six >=1.9.0,<2"
+    "python_abi 3.8.* *_cp38"
linux-64::virtualenv-20.16.3-py39h4162558_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9 *_pypy39_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.9 *_pypy39_pp73"
linux-64::virtualenv-20.16.3-py39hf3d152e_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9.* *_cp39",
-    "six >=1.9.0,<2"
+    "python_abi 3.9.* *_cp39"
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
linux-aarch64::virtualenv-20.16.3-py310hbbe02a8_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.10.* *_cp310",
-    "six >=1.9.0,<2"
+    "python_abi 3.10.* *_cp310"
linux-aarch64::virtualenv-20.16.3-py37hd9ded2f_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "importlib-metadata >=0.12",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "importlib-metadata >=4.8.3",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.7.* *_cp37m",
-    "six >=1.9.0,<2"
+    "python_abi 3.7.* *_cp37m"
linux-aarch64::virtualenv-20.16.3-py38h2063c64_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8.* *_cp38",
-    "six >=1.9.0,<2"
+    "python_abi 3.8.* *_cp38"
linux-aarch64::virtualenv-20.16.3-py38he37f277_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8 *_pypy38_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.8 *_pypy38_pp73"
linux-aarch64::virtualenv-20.16.3-py39ha65689a_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9.* *_cp39",
-    "six >=1.9.0,<2"
+    "python_abi 3.9.* *_cp39"
linux-aarch64::virtualenv-20.16.3-py39hdc1b86f_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9 *_pypy39_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.9 *_pypy39_pp73"
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
linux-ppc64le::virtualenv-20.16.3-py310hd032262_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.10.* *_cp310",
-    "six >=1.9.0,<2"
+    "python_abi 3.10.* *_cp310"
linux-ppc64le::virtualenv-20.16.3-py37h35e4cab_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "importlib-metadata >=0.12",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "importlib-metadata >=4.8.3",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.7.* *_cp37m",
-    "six >=1.9.0,<2"
+    "python_abi 3.7.* *_cp37m"
linux-ppc64le::virtualenv-20.16.3-py38hf1d151d_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8 *_pypy38_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.8 *_pypy38_pp73"
linux-ppc64le::virtualenv-20.16.3-py38hf8b3453_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8.* *_cp38",
-    "six >=1.9.0,<2"
+    "python_abi 3.8.* *_cp38"
linux-ppc64le::virtualenv-20.16.3-py39hb881913_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9 *_pypy39_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.9 *_pypy39_pp73"
linux-ppc64le::virtualenv-20.16.3-py39hc1b9086_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9.* *_cp39",
-    "six >=1.9.0,<2"
+    "python_abi 3.9.* *_cp39"
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::virtualenv-20.16.3-py310h2ec42d9_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.10.* *_cp310",
-    "six >=1.9.0,<2"
+    "python_abi 3.10.* *_cp310"
osx-64::virtualenv-20.16.3-py37hf985489_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "importlib-metadata >=0.12",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "importlib-metadata >=4.8.3",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.7.* *_cp37m",
-    "six >=1.9.0,<2"
+    "python_abi 3.7.* *_cp37m"
osx-64::virtualenv-20.16.3-py38h25b0044_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8 *_pypy38_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.8 *_pypy38_pp73"
osx-64::virtualenv-20.16.3-py38h50d1736_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8.* *_cp38",
-    "six >=1.9.0,<2"
+    "python_abi 3.8.* *_cp38"
osx-64::virtualenv-20.16.3-py39h43b90dd_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9 *_pypy39_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.9 *_pypy39_pp73"
osx-64::virtualenv-20.16.3-py39h6e9494a_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9.* *_cp39",
-    "six >=1.9.0,<2"
+    "python_abi 3.9.* *_cp39"
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
osx-arm64::virtualenv-20.16.3-py310hbe9552e_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.10.* *_cp310",
-    "six >=1.9.0,<2"
+    "python_abi 3.10.* *_cp310"
osx-arm64::virtualenv-20.16.3-py38h10201cd_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8.* *_cp38",
-    "six >=1.9.0,<2"
+    "python_abi 3.8.* *_cp38"
osx-arm64::virtualenv-20.16.3-py39h2804cbe_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9.* *_cp39",
-    "six >=1.9.0,<2"
+    "python_abi 3.9.* *_cp39"
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
win-64::virtualenv-20.16.3-py310h5588dad_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.10.* *_cp310",
-    "six >=1.9.0,<2"
+    "python_abi 3.10.* *_cp310"
win-64::virtualenv-20.16.3-py38h32ec214_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8 *_pypy38_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.8 *_pypy38_pp73"
win-64::virtualenv-20.16.3-py38haa244fe_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.8.* *_cp38",
-    "six >=1.9.0,<2"
+    "python_abi 3.8.* *_cp38"
win-64::virtualenv-20.16.3-py39h0d475fb_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9 *_pypy39_pp73",
-    "six >=1.9.0,<2"
+    "python_abi 3.9 *_pypy39_pp73"
win-64::virtualenv-20.16.3-py39hcbf5309_0.tar.bz2
-    "distlib >=0.3.1,<1",
-    "filelock >=3.2,<4",
-    "platformdirs >=2,<3",
+    "distlib >=0.3.5,<1",
+    "filelock >=3.4.1,<4",
+    "platformdirs >=2.4,<3",
-    "python_abi 3.9.* *_cp39",
-    "six >=1.9.0,<2"
+    "python_abi 3.9.* *_cp39"
```

This all looks as expected to me.

**Comment by maresb** [comment]
I just carefully reviewed this, and it looks correct to me.

**Comment by xylar** [comment]
@conda-forge/core, it seems like @ocefpaf may not be available to review this right now.  Is anyone else available?

**Comment by xylar** [comment]
@conda-forge/core and specifically @ocefpaf, has someone had a chance to take a look at this?

**Comment by maresb** [comment]
There is a large backlog on this repo. I think core is busy. :slightly_smiling_face:

**Comment by ocefpaf** [comment]
> There is a large backlog on this repo. I think core is busy. slightly_smiling_face

We all are, right? Thanks both of you for the patience and the fix!

**Comment by xylar** [comment]
Thanks @ocefpaf.  I totally get it about the backlog.  To horribly mix metaphors, sometimes you have to be the squeeky wheel :-)

**Pull request merged**
