### PR TITLE
Revised patches from #136 and #137 to fix missing py-tools-ds.similar module in old arosics versions.

### PR DESCRIPTION
**Pull request by danschef**
This is a revision of #136 and #137 because I noticed that the metadata changes from #137 were correctly applied (the conda package resolver respects the updated metadata) but the changes from #136 were not. I don´t know the reason for that but this PR should fix it.

@beckermr 

Below is the diff. Note that for some reason it changes `ruby-2.7.2-h82393f8_3.tar.bz2` although I did not patch it. Also it seems to have no effect to the arosics>=1.06,<=1.1.1 versions. Maybe because the patch from #137 was already correctly applied.
```
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::arosics-0.9.23-pyh9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
noarch::arosics-0.9.24-pyh9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
linux-64::arosics-0.9.24-py36h9f0ad1d_1.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.24-py36h9f0ad1d_2.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.24-py36h9f0ad1d_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.24-py37hc8dfbb8_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.24-py38h32f6830_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.25-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.25-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.25-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.26-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.26-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-0.9.26-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.0-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.0-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.0-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.1-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.1-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.1-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.2-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.2-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.2-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.3-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.3-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.3-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.5-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.5-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
linux-64::arosics-1.0.5-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
linux-aarch64::ruby-2.7.2-h82393f8_3.tar.bz2
-  "track_features": "rb27",
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
osx-64::arosics-0.9.24-py36h9f0ad1d_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.24-py37hc8dfbb8_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.24-py38h32f6830_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.25-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.25-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.25-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.26-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.26-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-0.9.26-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.0-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.0-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.0-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.1-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.1-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.1-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.2-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.2-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.2-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.3-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.3-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.3-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.5-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.5-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::arosics-1.0.5-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
osx-64::ruby-2.7.2-h36135d8_3.tar.bz2
-  "track_features": "rb27",
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
osx-arm64::ruby-2.7.2-h6b02988_3.tar.bz2
-  "track_features": "rb27",
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
win-64::arosics-0.9.24-py36h9f0ad1d_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.24-py37hc8dfbb8_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.24-py38h32f6830_3.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.25-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.25-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.25-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.26-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.26-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-0.9.26-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.0-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.0-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.0-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.1-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.1-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.1-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.2-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.2-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.2-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.3-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.3-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.3-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.5-py36h9f0ad1d_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.5-py37hc8dfbb8_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",
win-64::arosics-1.0.5-py38h32f6830_0.tar.bz2
-    "py-tools-ds >=0.14.28",
+    "py-tools-ds >=0.14.28,<=0.15.11",

```

### CODE REVIEW

**Comment by beckermr** [comment]
Don't worry about the changes to ruby.

**Comment by beckermr** [comment]
patches are always applied fresh from the raw metadata. so if you see no effect, it is a bug in the patching code.

**Comment by danschef** [comment]
I checked that again, in this case it is not a bug in the patching code. The `ref_repodata` dictionary [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/8db2cc951c982f4964de7d66dae587edf2708930/recipe/show_diff.py#L41) already contains the updated metadata from the patch in #137 but not the changes from #136.

That means the above diff should be correct and the patch should update only those metadata which was not updated before. I think you can merge it.

**Comment by danschef** [comment]
Thanks!

**Comment by danschef** [comment]
Works nicely.

**Pull request merged**
