### PR TITLE
ENH add mpi 1.0 impi metapackage pin for intel mpi

### PR DESCRIPTION
**Pull request by beckermr**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

<!-- Put any other comments or information here --!>

### CODE REVIEW

**Comment by beckermr** [comment]
Here is the diff

```
% python recipe/show_diff.py 
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
linux-ppc64le
================================================================================
================================================================================
linux-aarch64
================================================================================
================================================================================
noarch
================================================================================
================================================================================
win-64
win-64::impi_rt-2021.10.0-h57928b3_42.conda
win-64::impi_rt-2021.10.0-h57928b3_50372.conda
win-64::impi_rt-2021.10.0-h57928b3_43.conda
win-64::impi_rt-2021.10.0-h57928b3_49378.conda
win-64::impi_rt-2021.10.0-h57928b3_49379.conda
win-64::impi_rt-2021.10.0-h57928b3_41.conda
-  "depends": [],
+  "depends": [
+    "mpi 1.0 impi"
+  ],
win-64::mpi4py-3.1.5-py310headf037_0.conda
-{
-  "build": "py310headf037_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "python >=3.10,<3.11.0a0",
-    "python_abi 3.10.* *_cp310",
-    "ucrt >=10.0.20348.0",
-    "vc >=14.2,<15",
-    "vc14_runtime >=14.29.30139"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "27e8d1577a191dae64d84984395a9f56",
-  "name": "mpi4py",
-  "sha256": "531e5a63e8d3e89d961a14e09e4ef19979ce8e5ecdb9467dd00534630c2d9298",
-  "size": 414799,
-  "subdir": "win-64",
-  "timestamp": 1697530203885,
-  "version": "3.1.5"
-}
+{}
win-64::mpi4py-3.1.5-py311h752e774_0.conda
-{
-  "build": "py311h752e774_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "python >=3.11,<3.12.0a0",
-    "python_abi 3.11.* *_cp311",
-    "ucrt >=10.0.20348.0",
-    "vc >=14.2,<15",
-    "vc14_runtime >=14.29.30139"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "ea8823c2909b3bf316688e6c820b88d1",
-  "name": "mpi4py",
-  "sha256": "3cc2d8f8d7e0c94ac5e103a5c93040c7ce9951f1c21a9a19594358924ca54375",
-  "size": 436213,
-  "subdir": "win-64",
-  "timestamp": 1697530360915,
-  "version": "3.1.5"
-}
+{}
win-64::mpi4py-3.1.5-py312h5f1d38d_0.conda
-{
-  "build": "py312h5f1d38d_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "python >=3.12,<3.13.0a0",
-    "python_abi 3.12.* *_cp312",
-    "ucrt >=10.0.20348.0",
-    "vc >=14.2,<15",
-    "vc14_runtime >=14.29.30139"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "f89d42553c8e79d325a3596a40496054",
-  "name": "mpi4py",
-  "sha256": "3b72b0c882189c8209a5a670d736c777603f7c9e575f354a182a64cefacd2333",
-  "size": 435089,
-  "subdir": "win-64",
-  "timestamp": 1697530407396,
-  "version": "3.1.5"
-}
+{}
win-64::mpi4py-3.1.5-py38h6d6d2c7_0.conda
-{
-  "build": "py38h6d6d2c7_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "python >=3.8,<3.9.0a0",
-    "python_abi 3.8.* *_cp38",
-    "ucrt >=10.0.20348.0",
-    "vc >=14.2,<15",
-    "vc14_runtime >=14.29.30139"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "36f77f680d3078c30dcf08e759a70697",
-  "name": "mpi4py",
-  "sha256": "d6b4431e21358f56571ba5eef5b18711dfcbc5a2436ff3da5d14d51c1648874d",
-  "size": 420251,
-  "subdir": "win-64",
-  "timestamp": 1697530569911,
-  "version": "3.1.5"
-}
+{}
win-64::mpi4py-3.1.5-py39hc2a0298_0.conda
-{
-  "build": "py39hc2a0298_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "pypy3.9 >=7.3.13",
-    "python >=3.9,<3.10.0a0",
-    "python_abi 3.9 *_pypy39_pp73",
-    "ucrt >=10.0.20348.0",
-    "vc >=14.2,<15",
-    "vc14_runtime >=14.29.30139"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "192dba669e335bd424a7d3db6c8af6af",
-  "name": "mpi4py",
-  "sha256": "d2aa436f5f2c4263ecc087312f41765b6970f31cbdf8649eb0800b5be731b783",
-  "size": 402956,
-  "subdir": "win-64",
-  "timestamp": 1697530386048,
-  "version": "3.1.5"
-}
+{}
win-64::mpi4py-3.1.5-py39hd8a89ea_0.conda
-{
-  "build": "py39hd8a89ea_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "python >=3.9,<3.10.0a0",
-    "python_abi 3.9.* *_cp39",
-    "ucrt >=10.0.20348.0",
-    "vc >=14.2,<15",
-    "vc14_runtime >=14.29.30139"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "f5af783fa20f786847a6df861b2aaf5d",
-  "name": "mpi4py",
-  "sha256": "499753caba3b0d20518bd27fac2ca12dc8a0b4ba076255e792515a12f2c923c8",
-  "size": 416049,
-  "subdir": "win-64",
-  "timestamp": 1697530155663,
-  "version": "3.1.5"
-}
+{}
================================================================================
================================================================================
osx-64
================================================================================
================================================================================
linux-64
linux-64::impi_rt-2021.10.0-ha770c72_35.conda
linux-64::impi_rt-2021.10.0-ha770c72_49378.conda
linux-64::impi_rt-2021.10.0-ha770c72_50371.conda
linux-64::impi_rt-2021.10.0-ha770c72_36.conda
linux-64::impi_rt-2021.10.0-ha770c72_49377.conda
linux-64::impi_rt-2021.10.0-ha770c72_37.conda
-  "depends": [],
+  "depends": [
+    "mpi 1.0 impi"
+  ],
linux-64::mpi4py-3.1.5-py310h45b48a2_0.conda
-{
-  "build": "py310h45b48a2_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "libgcc-ng >=12",
-    "python >=3.10,<3.11.0a0",
-    "python_abi 3.10.* *_cp310"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "b34d71da0b7c48f2c5d38dd235376a4b",
-  "name": "mpi4py",
-  "sha256": "3e2c0c782466e902a6b9295919411807b751d426645375638b6391bb46deb020",
-  "size": 540910,
-  "subdir": "linux-64",
-  "timestamp": 1697529344444,
-  "version": "3.1.5"
-}
+{}
linux-64::mpi4py-3.1.5-py311he9ffdee_0.conda
-{
-  "build": "py311he9ffdee_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "libgcc-ng >=12",
-    "python >=3.11,<3.12.0a0",
-    "python_abi 3.11.* *_cp311"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "86a1b3c438a094aa1cb2085a31aa372c",
-  "name": "mpi4py",
-  "sha256": "51418a793af0dbd70e184aa162e96016e4dc7c2227d57bf44f0c788db8c17fc1",
-  "size": 567536,
-  "subdir": "linux-64",
-  "timestamp": 1697529275014,
-  "version": "3.1.5"
-}
+{}
linux-64::mpi4py-3.1.5-py312hac3760b_0.conda
-{
-  "build": "py312hac3760b_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "libgcc-ng >=12",
-    "python >=3.12,<3.13.0a0",
-    "python_abi 3.12.* *_cp312"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "775186a0ea1ab4c7791ec2fc7879b6b6",
-  "name": "mpi4py",
-  "sha256": "40a0dd260e4dff4bcdc08ea8315b71e69531dd97c1626304025da025cb7debba",
-  "size": 565136,
-  "subdir": "linux-64",
-  "timestamp": 1697529371476,
-  "version": "3.1.5"
-}
+{}
linux-64::mpi4py-3.1.5-py38h2675600_0.conda
-{
-  "build": "py38h2675600_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "libgcc-ng >=12",
-    "python >=3.8,<3.9.0a0",
-    "python_abi 3.8.* *_cp38"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "b776a33223fdb8d8d7d9fd0611a1f556",
-  "name": "mpi4py",
-  "sha256": "f32f0a7c0019474e1e1f813d2eae31c3161c35b17293d97c5602b699ccd0514b",
-  "size": 547709,
-  "subdir": "linux-64",
-  "timestamp": 1697529281038,
-  "version": "3.1.5"
-}
+{}
linux-64::mpi4py-3.1.5-py39h03e9507_0.conda
-{
-  "build": "py39h03e9507_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "libgcc-ng >=12",
-    "python >=3.9,<3.10.0a0",
-    "python_abi 3.9.* *_cp39"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "bd84677f6cac756a3074f133d8dd5e44",
-  "name": "mpi4py",
-  "sha256": "0bc1f48e11cf7650dc38433eff2fe7d42426bdb313ce4398c9e363399f0b8318",
-  "size": 543687,
-  "subdir": "linux-64",
-  "timestamp": 1697529322133,
-  "version": "3.1.5"
-}
+{}
linux-64::mpi4py-3.1.5-py39h635da37_0.conda
-{
-  "build": "py39h635da37_0",
-  "build_number": 0,
-  "depends": [
-    "impi_rt >=2021.10.0,<2022.0a0",
-    "libgcc-ng >=12",
-    "pypy3.9 >=7.3.13",
-    "python >=3.9,<3.10.0a0",
-    "python_abi 3.9 *_pypy39_pp73"
-  ],
-  "license": "BSD-2-Clause",
-  "md5": "7c961f25fbd6876675bf0bbb7d9496c4",
-  "name": "mpi4py",
-  "sha256": "e3eb0956b4d12c8a02a05709ff93d1be0efba3f7129a875b3dbd50b6e1547cd4",
-  "size": 524136,
-  "subdir": "linux-64",
-  "timestamp": 1697529366494,
-  "version": "3.1.5"
-}
+{}
```

ignore the mpi4py stuff - that is a mark broken job in the middle

**Comment by beckermr** [comment]
cc @conda-forge/intel_repack @conda-forge/mpi @leofang @dalcini This PR will make impi uninstalable until the proper mutex package exists. Is that OK?

**Comment by leofang** [comment]
xref: https://github.com/conda-forge/mpi-feedstock/pull/12

**Comment by beckermr** [comment]
merged! I'm going to merge here and the dust will clear in 20 minutes or so.

**Comment by leofang** [comment]
Thanks Matt for helping fire fighting!

**Pull request merged**
