### PR TITLE
pin tokenizers in transformers >=4.23,<4.34

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [ ] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

```diff
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
linux-ppc64le
================================================================================
================================================================================
linux-aarch64
================================================================================
================================================================================
noarch
noarch::transformers-4.27.4-pyhd8ed1ab_0.conda
noarch::transformers-4.27.1-pyhd8ed1ab_0.conda
noarch::transformers-4.28.1-pyhd8ed1ab_0.conda
noarch::transformers-4.29.1-pyhd8ed1ab_0.conda
noarch::transformers-4.28.0-pyhd8ed1ab_0.conda
noarch::transformers-4.27.3-pyhd8ed1ab_0.conda
noarch::transformers-4.26.0-pyhd8ed1ab_0.conda
noarch::transformers-4.27.2-pyhd8ed1ab_0.conda
noarch::transformers-4.29.2-pyhd8ed1ab_0.conda
noarch::transformers-4.26.1-pyhd8ed1ab_0.conda
noarch::transformers-4.24.0-pyhd8ed1ab_0.tar.bz2
noarch::transformers-4.23.0-pyhd8ed1ab_0.tar.bz2
noarch::transformers-4.29.0-pyhd8ed1ab_0.conda
noarch::transformers-4.23.1-pyhd8ed1ab_0.tar.bz2
-    "tokenizers >=0.11.1,!=0.11.3",
+    "tokenizers >=0.11.1,!=0.11.3,<0.14.0a0",
================================================================================
================================================================================
win-64
================================================================================
================================================================================
osx-64
================================================================================
================================================================================
linux-64

```

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/conda-forge-repodata-patches @conda-forge/transformers @conda-forge/core ready for review

**Review by beckermr — APPROVED** [review]
The extra comma at the end is a bit odd but hopefully that's something about how we are printing this out.

**Comment by beckermr** [comment]
oh nvm I missed the double quote!

**Comment by bollwyvl** [comment]
Thank you!

**Pull request merged**
