### PR TITLE
Pin dask dependency for older versions of dask-sql

### PR DESCRIPTION
**Pull request by charlesbluca**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

We are planning on pinning dask-sql's Dask dependency moving forward - this patch retroactively pins all older releases of dask-sql to their respective Dask version at time of release.

Marking this as draft for now until the relevant pinning happens in [dask-sql-feedstock](https://github.com/conda-forge/dask-sql-feedstock/).

### CODE REVIEW

**Comment by jakirkham** [comment]
Can you please [run `show_diff.py` locally]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/3d0277f04c7353c6ead6c9d00a612d533d378b88/recipe#readme ) and share the results here?

**Comment by charlesbluca** [comment]
Sure!

```
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::dask-sql-0.1.0rc2-py_0.tar.bz2
-    "dask >=2.19.0",
+    "dask ==2.26.0",
noarch::dask-sql-0.1.2-py_0.tar.bz2
-    "dask >=2.19.0",
+    "dask ==2.30.0",
noarch::dask-sql-0.2.0-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0",
+    "dask ==2.30.0",
noarch::dask-sql-0.2.2-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0",
+    "dask ==2.30.0",
noarch::dask-sql-0.3.0-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0",
+    "dask ==2021.1.0",
noarch::dask-sql-0.3.1-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0",
+    "dask ==2021.2.0",
noarch::dask-sql-0.3.2-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0,<=2021.2.0",
+    "dask ==2021.4.0",
noarch::dask-sql-0.3.3-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0,<=2021.2.0",
+    "dask ==2021.4.1",
noarch::dask-sql-0.3.4-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0,!=2021.3.0",
+    "dask ==2021.4.1",
noarch::dask-sql-0.3.6-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0,!=2021.3.0",
+    "dask ==2021.5.0",
noarch::dask-sql-0.3.9-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0,!=2021.3.0",
+    "dask ==2021.8.0",
noarch::dask-sql-0.4.0-pyhd8ed1ab_0.tar.bz2
-    "dask >=2.19.0,!=2021.3.0",
+    "dask ==2021.10.0",
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
```

**Comment by jakirkham** [comment]
Thanks Charles! 😄

Is this ready for review?

**Comment by charlesbluca** [comment]
Yes 🙂

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
