### PR TITLE
Constrain pydantic version

### PR DESCRIPTION
**Pull request by ijpulidos**
Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future.

### CODE REVIEW

**Comment by ijpulidos** [comment]
@conda-forge-admin Should be ready for review! Thanks.

**Comment by hmaarrfk** [comment]
is there a new version of feflow?

**Comment by ijpulidos** [comment]
@hmaarrfk No, just 0.1.0 for now. But there will be a new one coming soon (patch release supporting pydantic 2).

**Comment by ijpulidos** [comment]
@hmaarrfk Oh do you mean that this could have been done in the `feflow` feedstock itself? Maybe with a different build number, right?

**Comment by hmaarrfk** [comment]
I guess we typically like to patch once the underlying problem has been resolved in the feedstock itself.

**Comment by hmaarrfk** [comment]
so either a new build number with the constraint (that will be removed "momentarily") or a new version that makes the constraint obsolete.

**Comment by ijpulidos** [comment]
@hmaarrfk understood, let me do that!

**Comment by hmaarrfk** [comment]
you can also backport the "small patch"

**Comment by ijpulidos** [comment]
@hmaarrfk The feedstock should be fixed now https://github.com/conda-forge/feflow-feedstock/pull/1 is that enough to unblock this? Please let me know. Thank you for your support!

**Pull request merged**
