### PR TITLE
Fix expat pin to match run_exports

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Diff is at https://gist.github.com/isuruf/3229c63ac740b83aa1b932aa03c5d712

**Comment by isuruf** [comment]
@conda-forge/core, this is ready.

**Comment by beckermr** [comment]
Feel free to merge. The diff has a bunch zlib arrow and tbb patches in it. I don't know why things are being patched again like this, but it is not great. 

Not your problem though. Merge away.

**Review by beckermr — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
