### PR TITLE
Fix missing upper pins for cylc-rose

### PR DESCRIPTION
**Pull request by MetRonnie**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/cylc-rose-feedstock/issues/10 hopefully

### CODE REVIEW

**Comment by dopplershift** [comment]
Can you resolve the conflict and post the output of `show_diff.py`?

**Comment by MetRonnie** [comment]
I got 504 both times I tried to run it
```
$ python recipe/show_diff.py --use-cache
linux-64::cylc-rose-0.1.1-py37h89c1867_0.tar.bz2
-    "cylc-flow >=8.0b0",
-    "metomi-rose >=2.0b1",
+    "cylc-flow ==8.0b0",
+    "metomi-rose ==2.0b1",
linux-64::cylc-rose-0.1.1-py38h578d9bd_0.tar.bz2
-    "cylc-flow >=8.0b0",
-    "metomi-rose >=2.0b1",
+    "cylc-flow ==8.0b0",
+    "metomi-rose ==2.0b1",
linux-64::cylc-rose-0.2-py37h89c1867_0.tar.bz2
-    "cylc-flow >=8.0b2",
-    "metomi-rose >=2.0b2",
+    "cylc-flow ==8.0b2",
+    "metomi-rose ==2.0b2",
linux-64::cylc-rose-0.2-py38h578d9bd_0.tar.bz2
-    "cylc-flow >=8.0b2",
-    "metomi-rose >=2.0b2",
+    "cylc-flow ==8.0b2",
+    "metomi-rose ==2.0b2",
linux-64::cylc-rose-0.2-py39hf3d152e_0.tar.bz2
-    "cylc-flow >=8.0b2",
-    "metomi-rose >=2.0b2",
+    "cylc-flow ==8.0b2",
+    "metomi-rose ==2.0b2",
osx-64::cylc-rose-0.2-py37hf985489_0.tar.bz2
-    "cylc-flow >=8.0b2",
-    "metomi-rose >=2.0b2",
+    "cylc-flow ==8.0b2",
+    "metomi-rose ==2.0b2",
osx-64::cylc-rose-0.2-py38h50d1736_0.tar.bz2
-    "cylc-flow >=8.0b2",
-    "metomi-rose >=2.0b2",
+    "cylc-flow ==8.0b2",
+    "metomi-rose ==2.0b2",
osx-64::cylc-rose-0.2-py39h6e9494a_0.tar.bz2
-    "cylc-flow >=8.0b2",
-    "metomi-rose >=2.0b2",
+    "cylc-flow ==8.0b2",
+    "metomi-rose ==2.0b2",
Traceback (most recent call last):
  File "~/conda-forge-repodata-patches-feedstock/recipe/show_diff.py", line 88, in <module>
    do_subdir(subdir, raw_repodata_path, ref_repodata_path)
  File "~/conda-forge-repodata-patches-feedstock/recipe/show_diff.py", line 49, in do_subdir
    instructions = _gen_patch_instructions(raw_repodata, new_index, subdir)
  File "~/conda-forge-repodata-patches-feedstock/recipe/gen_patch_json.py", line 316, in _gen_patch_instructions
    _add_removals(instructions, subdir)
  File "~/conda-forge-repodata-patches-feedstock/recipe/gen_patch_json.py", line 296, in _add_removals
    r.raise_for_status()
  File "~/.conda/envs/tmp/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://conda.anaconda.org/conda-forge/label/broken/win-32/repodata.json
```

**Comment by zklaus** [comment]
@MetRonnie, could you try again? There may have been a temporary disturbance on the server, but I verified now that it works. If you keep having the error, I might try to produce the output.

**Comment by zklaus** [comment]
The changes look good to me. The changes to virtualenv seem indeed to come from the latest commit already in main. @dopplershift, could you please have another look?

**Comment by zklaus** [comment]
Sorry, @MetRonnie, I understand this is a bit frustrating, but could you resolve the new conflicts? Alternatively, if you add me to https://github.com/MetRonnie/conda-forge-repodata-patches-feedstock, I can do that.

**Comment by zklaus** [comment]
Thanks, @MetRonnie. @conda-forge/core, could somebody have a look?

**Pull request merged**
